branches:
  only:
  - develop
  - staging
dist: jammy
language: node_js
node_js:
  - 18
before_install:
  - node scripts/hack-travis.mjs
install:
  - npm ci
  - npm run prepare
script:
  - npm run lint
  - npx tsc
  - npm test
