import standardConfig from 'eslint-config-standard-kit'
import rnPlugin from 'eslint-plugin-react-native'

import edgePlugin from './scripts/eslint-plugin-edge/index.mjs'

export default [
  ...standardConfig({
    prettier: true,
    sortImports: true,
    node: true,
    react: true,
    typescript: true
  }),

  // Activate additional rules:
  {
    plugins: {
      'react-native': rnPlugin,
      edge: edgePlugin
    },
    rules: {
      // Tweak builtin rules:
      'react/jsx-handler-names': 'warn',

      // Add the React Native plugin:
      ...rnPlugin.configs.all.rules,
      'react-hooks/exhaustive-deps': [
        'error',
        {
          additionalHooks: '^useSceneFooterRender$'
        }
      ],
      'react-native/no-inline-styles': 'off',
      'react-native/no-raw-text': [
        'error',
        {
          skip: ['B', 'EdgeText', 'Paragraph', 'SmallText', 'WarningText']
        }
      ],
      'react-native/sort-styles': 'off',

      // Add our own rules:
      'edge/useAbortable-abort-check-param': 'error',
      'edge/useAbortable-abort-check-usage': 'error'
    }
  },

  // Turn several TypeScript lint errors into warnings:
  {
    files: [
      'scripts/createAndroidKeys.ts',
      'scripts/deploy.ts',
      'scripts/gitVersionFile.ts',
      'scripts/loggingServer.ts',
      'scripts/makeNativeHeaders.ts',
      'scripts/patchFiles.ts',
      'scripts/secretFiles.ts',
      'scripts/themeServer.ts',
      'scripts/updateVersion.ts',
      'src/__tests__/components/CreateWalletSelectCryptoRow.test.tsx',
      'src/__tests__/components/MenuTabs.test.tsx',
      'src/__tests__/utils.test.ts',
      'src/__tests__/utils/parseMarkedText.test.ts',
      'src/actions/BackupModalActions.tsx',
      'src/actions/CategoriesActions.ts',
      'src/actions/CountryListActions.tsx',
      'src/actions/CreateWalletActions.tsx',
      'src/actions/DeepLinkingActions.tsx',
      'src/actions/DeviceSettingsActions.ts',
      'src/actions/ExchangeRateActions.ts',
      'src/actions/FioActions.tsx',
      'src/actions/FioAddressActions.ts',
      'src/actions/FirstOpenActions.tsx',
      'src/actions/LoanWelcomeActions.tsx',
      'src/actions/LocalSettingsActions.ts',
      'src/actions/LogActions.tsx',
      'src/actions/LoginActions.tsx',
      'src/actions/NotificationActions.ts',
      'src/actions/PaymentProtoActions.tsx',
      'src/actions/ReceiveDropdown.tsx',
      'src/actions/RecoveryReminderActions.tsx',
      'src/actions/RequestReviewActions.tsx',
      'src/actions/ScamWarningActions.tsx',
      'src/actions/ScanActions.tsx',
      'src/actions/SettingsActions.tsx',
      'src/actions/SoundActions.ts',
      'src/actions/TokenTermsActions.tsx',
      'src/actions/TransactionExportActions.tsx',
      'src/actions/WalletActions.tsx',
      'src/actions/WalletListActions.tsx',
      'src/actions/WalletListMenuActions.tsx',
      'src/app.ts',
      'src/components/App.tsx',
      'src/components/buttons/ButtonsView.tsx',
      'src/components/buttons/EdgeSwitch.tsx',
      'src/components/buttons/IconButton.tsx',
      'src/components/buttons/MinimalButton.tsx',
      'src/components/buttons/ModalButtons.tsx',
      'src/components/buttons/ReturnKeyTypeButton.tsx',
      'src/components/buttons/SceneButtons.tsx',
      'src/components/cards/AdvancedDetailsCard.tsx',
      'src/components/cards/AlertCard.tsx',
      'src/components/cards/BalanceCard.tsx',
      'src/components/cards/EarnOptionCard.tsx',
      'src/components/cards/EdgeCard.tsx',
      'src/components/cards/FiatAmountInputCard.tsx',
      'src/components/cards/FiatExchangeDetailsCard.tsx',
      'src/components/cards/HomeTileCard.tsx',
      'src/components/cards/IconMessageCard.tsx',
      'src/components/cards/LoanDetailsSummaryCard.tsx',
      'src/components/cards/LoanSummaryCard.tsx',
      'src/components/cards/MarketsCard.tsx',
      'src/components/cards/StakingOptionCard.tsx',
      'src/components/cards/StakingReturnsCard.tsx',
      'src/components/cards/SupportCard.tsx',
      'src/components/cards/SwapDetailsCard.tsx',
      'src/components/cards/TappableAccountCard.tsx',
      'src/components/cards/TappableCard.tsx',
      'src/components/cards/UnderlinedNumInputCard.tsx',
      'src/components/cards/VisaCardCard.tsx',
      'src/components/cards/WalletRestoreCard.tsx',
      'src/components/cards/WarningCard.tsx',
      'src/components/charts/SwipeChart.tsx',
      'src/components/common/AirshipToast.tsx',
      'src/components/common/AnimatedNumber.tsx',
      'src/components/common/BlurBackground.tsx',
      'src/components/common/CrossFade.tsx',
      'src/components/common/DotsBackground.tsx',
      'src/components/common/EdgeAnim.tsx',
      'src/components/common/ExpandableList.tsx',
      'src/components/common/QrPeephole.tsx',
      'src/components/common/SceneWrapper.tsx',
      'src/components/common/SectionHeader.tsx',
      'src/components/common/TextDropdown.tsx',
      'src/components/FioAddress/ConnectWallets.tsx',
      'src/components/FioAddress/DomainListModal.tsx',
      'src/components/FioAddress/FioActionSubmit.tsx',
      'src/components/FioAddress/FioName.tsx',
      'src/components/hoc/maybeComponent.tsx',
      'src/components/hoc/styled.tsx',
      'src/components/hoc/withExtendedTouchable.tsx',
      'src/components/icons/CryptoIcon.tsx',
      'src/components/icons/FiatIcon.tsx',
      'src/components/icons/IconBadge.tsx',
      'src/components/icons/PairIcons.tsx',
      'src/components/icons/SwipeableRowIcon.tsx',
      'src/components/icons/WalletIcon.tsx',
      'src/components/keyboard/KavButton.tsx',

      'src/components/layout/Peek.tsx',
      'src/components/layout/SceneContainer.tsx',
      'src/components/modals/AccelerateTxModal.tsx',
      'src/components/modals/AddressModal.tsx',
      'src/components/modals/AirshipFullScreenSpinner.tsx',
      'src/components/modals/AutoLogoutModal.tsx',
      'src/components/modals/BackupModal.tsx',
      'src/components/modals/ButtonsModal.tsx',
      'src/components/modals/CategoryModal.tsx',
      'src/components/modals/ConfirmContinueModal.tsx',
      'src/components/modals/ContactListModal.tsx',
      'src/components/modals/ContactsPermissionModal.tsx',
      'src/components/modals/CountryListModal.tsx',
      'src/components/modals/DateModal.tsx',
      'src/components/modals/FiatListModal.tsx',
      'src/components/modals/FioCreateHandleModal.tsx',
      'src/components/modals/FioExpiredModal.tsx',
      'src/components/modals/FlipInputModal2.tsx',
      'src/components/modals/FundAccountModal.tsx',
      'src/components/modals/GradientFadeout.tsx',
      'src/components/modals/HelpModal.tsx',
      'src/components/modals/InsufficientFeesModal.tsx',
      'src/components/modals/ListModal.tsx',
      'src/components/modals/LoanWelcomeModal.tsx',
      'src/components/modals/LogsModal.tsx',
      'src/components/modals/PasswordReminderModal.tsx',
      'src/components/modals/PermissionsSettingModal.tsx',
      'src/components/modals/QrModal.tsx',
      'src/components/modals/RadioListModal.tsx',
      'src/components/modals/RawTextModal.tsx',
      'src/components/modals/ScamWarningModal.tsx',
      'src/components/modals/ScanModal.tsx',
      'src/components/modals/StateProvinceListModal.tsx',
      'src/components/modals/SurveyModal.tsx',
      'src/components/modals/SwapVerifyTermsModal.tsx',
      'src/components/modals/TextInputModal.tsx',
      'src/components/modals/TransferModal.tsx',
      'src/components/modals/WalletListMenuModal.tsx',
      'src/components/modals/WalletListModal.tsx',
      'src/components/modals/WalletListSortModal.tsx',
      'src/components/modals/WcSmartContractModal.tsx',
      'src/components/modals/WebViewModal.tsx',
      'src/components/navigation/AlertDropdown.tsx',
      'src/components/navigation/BackButton.tsx',
      'src/components/navigation/CurrencySettingsTitle.tsx',
      'src/components/navigation/EdgeHeader.tsx',
      'src/components/navigation/EdgeLogoHeader.tsx',
      'src/components/navigation/FlashNotification.tsx',
      'src/components/navigation/GuiPluginBackButton.tsx',
      'src/components/navigation/HeaderBackground.tsx',
      'src/components/navigation/HeaderTextButton.tsx',
      'src/components/navigation/HeaderTitle.tsx',
      'src/components/navigation/NavigationButton.tsx',
      'src/components/navigation/ParamHeaderTitle.tsx',
      'src/components/navigation/SideMenuButton.tsx',
      'src/components/navigation/TransactionDetailsTitle.tsx',
      'src/components/notification/NotificationCard.tsx',
      'src/components/notification/NotificationCenterCard.tsx',
      'src/components/notification/NotificationView.tsx',
      'src/components/progress-indicators/AccountSyncBar.tsx',
      'src/components/progress-indicators/CancellableProcessingScene.tsx',
      'src/components/progress-indicators/CircleTimer.tsx',
      'src/components/progress-indicators/FillLoader.tsx',
      'src/components/progress-indicators/FullScreenLoader.tsx',
      'src/components/progress-indicators/LoadingSplashScreen.tsx',
      'src/components/progress-indicators/Shimmer.tsx',
      'src/components/progress-indicators/StepProgressBar.tsx',
      'src/components/progress-indicators/WalletSyncCircle.tsx',
      'src/components/rows/CoinRankRow.tsx',
      'src/components/rows/CryptoFiatAmountRow.tsx',
      'src/components/rows/CurrencyRow.tsx',
      'src/components/rows/CustomAssetRow.tsx',
      'src/components/rows/EdgeRow.tsx',
      'src/components/rows/IconDataRow.tsx',
      'src/components/rows/PaymentMethodRow.tsx',
      'src/components/rows/SwapProviderRow.tsx',
      'src/components/rows/TxCryptoAmountRow.tsx',
      'src/components/scenes/AssetSettingsScene.tsx',
      'src/components/scenes/ChangeMiningFeeScene.tsx',
      'src/components/scenes/ChangePasswordScene.tsx',
      'src/components/scenes/ChangePinScene.tsx',
      'src/components/scenes/ChangeUsernameScene.tsx',
      'src/components/scenes/CoinRankingDetailsScene.tsx',
      'src/components/scenes/CoinRankingScene.tsx',
      'src/components/scenes/ConfirmScene.tsx',
      'src/components/scenes/CreateWalletAccountSelectScene.tsx',
      'src/components/scenes/CreateWalletAccountSetupScene.tsx',
      'src/components/scenes/CreateWalletCompletionScene.tsx',
      'src/components/scenes/CreateWalletEditNameScene.tsx',
      'src/components/scenes/CreateWalletImportOptionsScene.tsx',
      'src/components/scenes/CreateWalletImportScene.tsx',
      'src/components/scenes/CreateWalletSelectCryptoScene.tsx',
      'src/components/scenes/CurrencyNotificationScene.tsx',
      'src/components/scenes/CurrencySettingsScene.tsx',
      'src/components/scenes/DefaultFiatSettingScene.tsx',
      'src/components/scenes/DevTestScene.tsx',
      'src/components/scenes/DuressModeHowToScene.tsx',
      'src/components/scenes/DuressModeSettingScene.tsx',
      'src/components/scenes/DuressPinScene.tsx',
      'src/components/scenes/EdgeLoginScene.tsx',
      'src/components/scenes/EditTokenScene.tsx',
      'src/components/scenes/ExtraTabScene.tsx',
      'src/components/scenes/Fio/FioAddressDetailsScene.tsx',
      'src/components/scenes/Fio/FioAddressListScene.tsx',
      'src/components/scenes/Fio/FioAddressRegisteredScene.tsx',
      'src/components/scenes/Fio/FioAddressRegisterScene.tsx',
      'src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx',
      'src/components/scenes/Fio/FioAddressSettingsScene.tsx',
      'src/components/scenes/Fio/FioConnectWalletConfirmScene.tsx',
      'src/components/scenes/Fio/FioCreateHandleScene.tsx',
      'src/components/scenes/Fio/FioDomainRegisterScene.tsx',
      'src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx',
      'src/components/scenes/Fio/FioDomainSettingsScene.tsx',
      'src/components/scenes/Fio/FioNameConfirmScene.tsx',
      'src/components/scenes/Fio/FioRequestConfirmationScene.tsx',
      'src/components/scenes/Fio/FioRequestListScene.tsx',
      'src/components/scenes/Fio/FioSentRequestDetailsScene.tsx',
      'src/components/scenes/Fio/FioStakingChangeScene.tsx',
      'src/components/scenes/Fio/FioStakingOverviewScene.tsx',
      'src/components/scenes/FormScene.tsx',
      'src/components/scenes/GettingStartedScene.tsx',
      'src/components/scenes/GuiPluginListScene.tsx',
      'src/components/scenes/inputs/DigitInput.tsx',
      'src/components/scenes/inputs/DigitInput/PinDots.tsx',
      'src/components/scenes/LoadingScene.tsx',
      'src/components/scenes/Loans/LoanCloseScene.tsx',
      'src/components/scenes/Loans/LoanCreateConfirmationScene.tsx',
      'src/components/scenes/Loans/LoanCreateScene.tsx',
      'src/components/scenes/Loans/LoanDashboardScene.tsx',
      'src/components/scenes/Loans/LoanDetailsScene.tsx',
      'src/components/scenes/Loans/LoanManageScene.tsx',
      'src/components/scenes/Loans/LoanStatusScene.tsx',
      'src/components/scenes/LoginScene.tsx',
      'src/components/scenes/ManageTokensScene.tsx',
      'src/components/scenes/MigrateWalletCalculateFeeScene.tsx',
      'src/components/scenes/MigrateWalletCompletionScene.tsx',
      'src/components/scenes/MigrateWalletSelectCryptoScene.tsx',
      'src/components/scenes/NotificationCenterScene.tsx',
      'src/components/scenes/NotificationScene.tsx',
      'src/components/scenes/OtpRepairScene.tsx',
      'src/components/scenes/OtpSettingsScene.tsx',
      'src/components/scenes/PasswordRecoveryScene.tsx',
      'src/components/scenes/PromotionSettingsScene.tsx',
      'src/components/scenes/RequestScene.tsx',
      'src/components/scenes/ReviewTriggerTestScene.tsx',
      'src/components/scenes/SecurityAlertsScene.tsx',
      'src/components/scenes/SendScene2.tsx',
      'src/components/scenes/SettingsScene.tsx',
      'src/components/scenes/SpendingLimitsScene.tsx',
      'src/components/scenes/Staking/EarnScene.tsx',
      'src/components/scenes/Staking/StakeModifyScene.tsx',
      'src/components/scenes/Staking/StakeOptionsScene.tsx',
      'src/components/scenes/SwapConfirmationScene.tsx',
      'src/components/scenes/SwapCreateScene.tsx',
      'src/components/scenes/SwapProcessingScene.tsx',
      'src/components/scenes/SwapSettingsScene.tsx',
      'src/components/scenes/SwapSuccessScene.tsx',
      'src/components/scenes/SweepPrivateKeyCalculateFeeScene.tsx',
      'src/components/scenes/SweepPrivateKeyCompletionScene.tsx',
      'src/components/scenes/SweepPrivateKeyProcessingScene.tsx',
      'src/components/scenes/SweepPrivateKeySelectCryptoScene.tsx',
      'src/components/scenes/TransactionDetailsScene.tsx',
      'src/components/scenes/TransactionListScene.tsx',
      'src/components/scenes/TransactionsExportScene.tsx',
      'src/components/scenes/UpgradeUsernameScreen.tsx',
      'src/components/scenes/WalletListScene.tsx',
      'src/components/scenes/WalletRestoreScene.tsx',
      'src/components/scenes/WcConnectionsScene.tsx',
      'src/components/scenes/WcConnectScene.tsx',
      'src/components/scenes/WcDisconnectScene.tsx',
      'src/components/scenes/WebViewScene.tsx',
      'src/components/services/AccountCallbackManager.tsx',
      'src/components/services/ActionQueueService.ts',
      'src/components/services/AirshipInstance.tsx',
      'src/components/services/AutoLogout.ts',
      'src/components/services/ContactsLoader.ts',
      'src/components/services/DeepLinkingManager.tsx',
      'src/components/services/EdgeContextCallbackManager.tsx',
      'src/components/services/EdgeCoreManager.tsx',
      'src/components/services/FioService.ts',
      'src/components/services/LoanManagerService.ts',
      'src/components/services/NetworkActivity.ts',
      'src/components/services/NotificationService.ts',
      'src/components/services/PasswordReminderService.ts',
      'src/components/services/PermissionsManager.tsx',
      'src/components/services/Providers.tsx',

      'src/components/services/SortedWalletList.ts',
      'src/components/services/StatusBarManager.tsx',
      'src/components/services/WalletConnectService.tsx',
      'src/components/services/WalletLifecycle.ts',
      'src/components/services/WipeLogsService.tsx',
      'src/components/settings/SettingsHeaderRow.tsx',
      'src/components/settings/SettingsLabelRow.tsx',
      'src/components/settings/SettingsRadioRow.tsx',
      'src/components/settings/SettingsRow.tsx',
      'src/components/settings/SettingsSubHeader.tsx',
      'src/components/settings/SettingsSwitchRow.tsx',
      'src/components/settings/SettingsTappableRow.tsx',
      'src/components/text/AssetChangeText.tsx',
      'src/components/text/FiatText.tsx',

      'src/components/text/SectionHeading.tsx',
      'src/components/text/TitleText.tsx',
      'src/components/themed/AddressQr.tsx',
      'src/components/themed/Alert.tsx',
      'src/components/themed/BuyCrypto.tsx',
      'src/components/themed/CreateWalletSelectCryptoRow.tsx',
      'src/components/themed/DividerLine.tsx',
      'src/components/themed/EdgeProviderComponent.tsx',
      'src/components/themed/EdgeText.tsx',
      'src/components/themed/ExchangedFlipInput2.tsx',
      'src/components/themed/ExchangeQuoteComponent.tsx',
      'src/components/themed/ExplorerCard.tsx',
      'src/components/themed/Fade.tsx',

      'src/components/themed/FioRequestRow.tsx',

      'src/components/themed/LineTextDivider.tsx',
      'src/components/themed/MainButton.tsx',
      'src/components/themed/ManageTokensRow.tsx',
      'src/components/themed/MaybeCustomServersSetting.tsx',
      'src/components/themed/MaybeMoneroUserSettings.tsx',
      'src/components/themed/MenuTabs.tsx',
      'src/components/themed/ModalParts.tsx',
      'src/components/themed/PinDots.tsx',
      'src/components/themed/QrCode.tsx',
      'src/components/themed/SafeSlider.tsx',
      'src/components/themed/SceneFooterWrapper.tsx',
      'src/components/themed/SceneHeader.tsx',
      'src/components/themed/SceneHeaderUi4.tsx',
      'src/components/themed/SearchFooter.tsx',
      'src/components/themed/SelectableRow.tsx',
      'src/components/themed/SendFromFioRows.tsx',
      'src/components/themed/ShareButtons.tsx',
      'src/components/themed/SideMenu.tsx',
      'src/components/themed/SimpleTextInput.tsx',
      'src/components/themed/Slider.tsx',
      'src/components/themed/SwapInput.tsx',
      'src/components/themed/SwipeableRow.tsx',
      'src/components/themed/ThemedButtons.tsx',
      'src/components/themed/Thermostat.tsx',
      'src/components/themed/Title.tsx',
      'src/components/themed/TransactionListComponents.tsx',
      'src/components/themed/TransactionListRow.tsx',
      'src/components/themed/TransactionListTop.tsx',
      'src/components/themed/VectorIcon.tsx',
      'src/components/themed/WalletList.tsx',
      'src/components/themed/WalletListCreateRow.tsx',
      'src/components/themed/WalletListCurrencyRow.tsx',
      'src/components/themed/WalletListErrorRow.tsx',
      'src/components/themed/WalletListHeader.tsx',
      'src/components/themed/WalletListLoadingRow.tsx',
      'src/components/themed/WalletListSectionHeader.tsx',
      'src/components/themed/WalletListSortable.tsx',
      'src/components/themed/WalletListSortableRow.tsx',
      'src/components/themed/WalletListSwipeable.tsx',
      'src/components/themed/WalletListSwipeableCurrencyRow.tsx',
      'src/components/themed/WalletListSwipeableLoadingRow.tsx',
      'src/components/tiles/AddressTile2.tsx',
      'src/components/tiles/AprCard.tsx',
      'src/components/tiles/CountdownTile.tsx',
      'src/components/tiles/CryptoFiatAmountTile.tsx',
      'src/components/tiles/EditableAmountTile.tsx',
      'src/components/tiles/ErrorTile.tsx',
      'src/components/tiles/FiatAmountTile.tsx',
      'src/components/tiles/InterestRateChangeTile.tsx',
      'src/components/tiles/LtvRatioTile.tsx',
      'src/components/tiles/NetworkFeeTile.tsx',
      'src/components/tiles/PercentageChangeArrowTile.tsx',
      'src/components/tiles/TotalDebtCollateralTile.tsx',
      'src/constants/WalletAndCurrencyConstants.ts',
      'src/controllers/action-queue/ActionQueueStore.ts',
      'src/controllers/action-queue/cleaners.ts',
      'src/controllers/action-queue/push.ts',
      'src/controllers/action-queue/runtime/evaluateAction.ts',
      'src/controllers/action-queue/runtime/executeActionProgram.ts',
      'src/controllers/edgeProvider/client/edgeProviderBridge.ts',
      'src/controllers/edgeProvider/client/pendingList.ts',
      'src/controllers/edgeProvider/EdgeProviderServer.tsx',
      'src/controllers/loan-manager/borrowPluginConfig.ts',
      'src/controllers/loan-manager/redux/actions.ts',
      'src/controllers/loan-manager/util/waitForLoanAccountSync.ts',
      'src/hooks/animations/useFadeAnimation.ts',
      'src/hooks/redux/useContactThumbnail.ts',
      'src/hooks/useAbortable.ts',
      'src/hooks/useAccountSyncRatio.tsx',
      'src/hooks/useAsyncEffect.ts',
      'src/hooks/useAsyncNavigation.tsx',
      'src/hooks/useBackButtonToast.tsx',
      'src/hooks/useCryptoText.ts',
      'src/hooks/useExperimentConfig.ts',
      'src/hooks/useFiatText.ts',
      'src/hooks/useFilter.ts',
      'src/hooks/useHistoricalRate.ts',
      'src/hooks/useIconColor.ts',
      'src/hooks/useIsAccountFunded.ts',
      'src/hooks/useLayout.ts',
      'src/hooks/useLayoutOnce.ts',
      'src/hooks/useMount.ts',
      'src/hooks/usePendingPress.ts',
      'src/hooks/useRefresher.ts',
      'src/hooks/useScrollToEnd.ts',
      'src/hooks/useSharedEvent.ts',
      'src/hooks/useTokenDisplayData.ts',
      'src/hooks/useTransactionList.ts',
      'src/hooks/useUnmount.ts',
      'src/hooks/useWalletConnect.tsx',
      'src/hooks/useWalletsSubscriber.ts',
      'src/hooks/useWhyDidYouUpdate.ts',
      'src/locales/intl.ts',
      'src/locales/strings.ts',
      'src/plugins/borrow-plugins/common/ApprovableCall.ts',
      'src/plugins/borrow-plugins/common/cleaners/asBigNumber.ts',
      'src/plugins/borrow-plugins/plugins/aave/AaveBorrowEngineFactory.ts',
      'src/plugins/borrow-plugins/plugins/aave/index.ts',
      'src/plugins/gui/amountQuotePlugin.ts',
      'src/plugins/gui/components/GuiFormField.tsx',
      'src/plugins/gui/fiatPlugin.tsx',
      'src/plugins/gui/pluginUtils.ts',
      'src/plugins/gui/providers/banxaProvider.ts',
      'src/plugins/gui/providers/bityProvider.ts',
      'src/plugins/gui/providers/ioniaProvider.ts',
      'src/plugins/gui/providers/kadoOtcProvider.ts',
      'src/plugins/gui/providers/kadoProvider.ts',
      'src/plugins/gui/providers/moonpayProvider.ts',
      'src/plugins/gui/providers/mtpelerinProvider.ts',
      'src/plugins/gui/providers/paybisProvider.ts',
      'src/plugins/gui/providers/revolutProvider.ts',
      'src/plugins/gui/providers/simplexProvider.ts',
      'src/plugins/gui/RewardsCardPlugin.tsx',
      'src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx',
      'src/plugins/gui/scenes/FiatPluginWebView.tsx',
      'src/plugins/gui/scenes/InfoDisplayScene.tsx',
      'src/plugins/gui/scenes/RewardsCardDashboardScene.tsx',
      'src/plugins/gui/scenes/RewardsCardWelcomeScene.tsx',
      'src/plugins/gui/scenes/SepaFormScene.tsx',
      'src/plugins/gui/util/fetchRevolut.ts',
      'src/plugins/gui/util/initializeProviders.ts',
      'src/plugins/stake-plugins/currency/tronStakePlugin.ts',
      'src/plugins/stake-plugins/generic/pluginInfo/optimismTarotPool.ts',
      'src/plugins/stake-plugins/generic/policyAdapters/CardanoKilnAdaptor.ts',
      'src/plugins/stake-plugins/generic/policyAdapters/EthereumKilnAdaptor.ts',
      'src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts',
      'src/plugins/stake-plugins/generic/policyAdapters/TarotPoolAdaptor.ts',
      'src/plugins/stake-plugins/generic/policyAdapters/ThorchainYieldAdaptor.ts',
      'src/plugins/stake-plugins/generic/util/EdgeWalletSigner.ts',
      'src/plugins/stake-plugins/generic/util/KilnApi.ts',
      'src/plugins/stake-plugins/generic/util/tarotUtils.ts',
      'src/plugins/stake-plugins/metadataCache.ts',
      'src/plugins/stake-plugins/stakePlugins.ts',
      'src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.tsx',
      'src/plugins/stake-plugins/thorchainSavers/tcSaversPluginSegwit.tsx',
      'src/plugins/stake-plugins/uniswapV2/Ecosystem.ts',
      'src/plugins/stake-plugins/uniswapV2/policies/cemeteryPolicy.ts',
      'src/plugins/stake-plugins/uniswapV2/policies/masonryPolicy.ts',
      'src/plugins/stake-plugins/uniswapV2/policies/VelodromeV2StakePolicy.ts',
      'src/plugins/stake-plugins/util/accumulator.ts',
      'src/plugins/stake-plugins/util/biggystringplus.ts',
      'src/plugins/stake-plugins/util/builder.ts',
      'src/reducers/ExchangeInfoReducer.ts',
      'src/reducers/NetworkReducer.ts',
      'src/reducers/PasswordReminderReducer.ts',
      'src/reducers/scenes/SettingsReducer.ts',
      'src/reducers/SpendingLimitsReducer.ts',
      'src/selectors/getCreateWalletList.ts',
      'src/selectors/SettingsSelectors.ts',
      'src/state/createStateProvider.tsx',
      'src/state/SceneFooterState.tsx',
      'src/state/SceneScrollState.tsx',
      'src/styles/common/textStyles.tsx',
      'src/styles/common/textStylesThemed.ts',
      'src/types/reactRedux.ts',
      'src/util/addMetadataToContext.ts',
      'src/util/borrowUtils.ts',
      'src/util/cleaners.ts',
      'src/util/cleanFetch.ts',
      'src/util/crypto.ts',
      'src/util/CryptoAmount.ts',
      'src/util/cryptoTextUtils.ts',
      'src/util/CurrencyInfoHelpers.ts',
      'src/util/CurrencyWalletHelpers.ts',
      'src/util/DeepLinkParser.ts',
      'src/util/exchangeRates.ts',
      'src/util/fake/FakeProviders.tsx',
      'src/util/FioAddressUtils.ts',
      'src/util/getAccountUsername.ts',
      'src/util/GuiPluginTools.ts',
      'src/util/haptic.ts',
      'src/util/infoUtils.ts',
      'src/util/logger.ts',
      'src/util/maestro.ts',
      'src/util/memoUtils.ts',
      'src/util/middleware/perfLogger.ts',

      'src/util/otpReminder.tsx',
      'src/util/scaling.ts',
      'src/util/show-confetti.ts',
      'src/util/stakeUtils.ts',
      'src/util/tracking.ts',
      'src/util/ukComplianceUtils.ts',
      'src/util/utils.ts',
      'src/util/WebUtils.ts',
      'src/util/withWatchableProps.ts'
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname
      }
    },
    rules: {
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/default-param-last': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'warn',
      '@typescript-eslint/no-dynamic-delete': 'warn',
      '@typescript-eslint/no-misused-promises': 'warn',
      '@typescript-eslint/prefer-nullish-coalescing': 'warn',
      '@typescript-eslint/prefer-optional-chain': 'warn',
      '@typescript-eslint/require-array-sort-compare': 'warn',
      '@typescript-eslint/restrict-plus-operands': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'warn',
      '@typescript-eslint/strict-boolean-expressions': 'warn',
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'warn'
    }
  },

  // Global ignores need to be in their own block:
  {
    ignores: [
      '**/scratch.*',
      'android/*',
      'artifacts/*',
      'ios/*',
      'src/plugins/contracts/*',
      'src/controllers/edgeProvider/client/rolledUp.js',
      'src/controllers/edgeProvider/injectThisInWebView.js'
    ]
  }
]
