// flow-typed signature: be23322843e914b2d4b6a4b8df330fb2
// flow-typed version: <<STUB>>/airbitz-core-react-native_vgit://github.com/Airbitz/airbitz-core-react-native.git/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbitz-core-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbitz-core-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbitz-core-react-native/lib/airbitz-core-react-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbitz-core-react-native/lib/airbitz-core-react-native.js' {
  declare module.exports: $Exports<'airbitz-core-react-native/lib/airbitz-core-react-native'>;
}
