// flow-typed signature: 2fef92e08176581d3f6e1da14d2586a8
// flow-typed version: <<STUB>>/airbitz-exchange-plugins_vgit://github.com/Airbitz/airbitz-exchange-plugins.git/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbitz-exchange-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbitz-exchange-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbitz-exchange-plugins/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'airbitz-exchange-plugins/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbitz-exchange-plugins/lib/index.cjs.js' {
  declare module.exports: $Exports<'airbitz-exchange-plugins/lib/index.cjs'>;
}
declare module 'airbitz-exchange-plugins/lib/index.js' {
  declare module.exports: $Exports<'airbitz-exchange-plugins/lib/index'>;
}
