// flow-typed signature: 61179203f32e21b7bc1d090b07061305
// flow-typed version: <<STUB>>/browserify-zlib_v^0.1.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-zlib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-zlib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify-zlib/src/binding' {
  declare module.exports: any;
}

declare module 'browserify-zlib/src/index' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/ignored/test-zlib-dictionary-fail' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/ignored/test-zlib-dictionary' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/ignored/test-zlib-params' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-close-after-write' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-convenience-methods' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-from-string' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-invalid-input' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-random-byte-pipes' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-write-after-flush' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib-zero-byte' {
  declare module.exports: any;
}

declare module 'browserify-zlib/test/test-zlib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify-zlib/src/binding.js' {
  declare module.exports: $Exports<'browserify-zlib/src/binding'>;
}
declare module 'browserify-zlib/src/index.js' {
  declare module.exports: $Exports<'browserify-zlib/src/index'>;
}
declare module 'browserify-zlib/test/ignored/test-zlib-dictionary-fail.js' {
  declare module.exports: $Exports<'browserify-zlib/test/ignored/test-zlib-dictionary-fail'>;
}
declare module 'browserify-zlib/test/ignored/test-zlib-dictionary.js' {
  declare module.exports: $Exports<'browserify-zlib/test/ignored/test-zlib-dictionary'>;
}
declare module 'browserify-zlib/test/ignored/test-zlib-params.js' {
  declare module.exports: $Exports<'browserify-zlib/test/ignored/test-zlib-params'>;
}
declare module 'browserify-zlib/test/test-zlib-close-after-write.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-close-after-write'>;
}
declare module 'browserify-zlib/test/test-zlib-convenience-methods.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-convenience-methods'>;
}
declare module 'browserify-zlib/test/test-zlib-from-string.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-from-string'>;
}
declare module 'browserify-zlib/test/test-zlib-invalid-input.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-invalid-input'>;
}
declare module 'browserify-zlib/test/test-zlib-random-byte-pipes.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-random-byte-pipes'>;
}
declare module 'browserify-zlib/test/test-zlib-write-after-flush.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-write-after-flush'>;
}
declare module 'browserify-zlib/test/test-zlib-zero-byte.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib-zero-byte'>;
}
declare module 'browserify-zlib/test/test-zlib.js' {
  declare module.exports: $Exports<'browserify-zlib/test/test-zlib'>;
}
