// flow-typed signature: 058d021dc1747483d7984a6ac0fdd4c4
// flow-typed version: <<STUB>>/constants-browserify_v0.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constants-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'constants-browserify' {
  declare module.exports: any;
}
