// flow-typed signature: 8520eeacaa0bd3d944ef9d491ea3d64c
// flow-typed version: <<STUB>>/currency-symbol-map_v^4.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'currency-symbol-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'currency-symbol-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'currency-symbol-map/currency-symbol-map' {
  declare module.exports: any;
}

declare module 'currency-symbol-map/map' {
  declare module.exports: any;
}

declare module 'currency-symbol-map/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'currency-symbol-map/currency-symbol-map.js' {
  declare module.exports: $Exports<'currency-symbol-map/currency-symbol-map'>;
}
declare module 'currency-symbol-map/map.js' {
  declare module.exports: $Exports<'currency-symbol-map/map'>;
}
declare module 'currency-symbol-map/test.js' {
  declare module.exports: $Exports<'currency-symbol-map/test'>;
}
