// flow-typed signature: c45d53fe0e35bf553b7216ee2a6fcba3
// flow-typed version: <<STUB>>/domain-browser_v^1.1.7/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'domain-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'domain-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'domain-browser/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'domain-browser/index' {
  declare module.exports: $Exports<'domain-browser'>;
}
declare module 'domain-browser/index.js' {
  declare module.exports: $Exports<'domain-browser'>;
}
declare module 'domain-browser/test.js' {
  declare module.exports: $Exports<'domain-browser/test'>;
}
