// flow-typed signature: 03e8c816e79cd81d53754131468bdef9
// flow-typed version: <<STUB>>/edge-login-ui-rn_v0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'edge-login-ui-rn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'edge-login-ui-rn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'edge-login-ui-rn/src/common/actions/ChangePasswordPinActions' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/CreateAccountActions' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/LoginAction' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/PasswordRecoveryActions' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/PreviousUsersActions' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/UserActions' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/actions/WorkflowActions' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/Colors' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/ErrorConstants' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/Fonts' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/IconConstants' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/OtpConstants' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/Theme' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/constants/ToLocalizeConstants' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/dataHelpers/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/dataHelpers/PasswordEvalHelper' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/locale/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/locale/translations' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/locale/traslationKeys' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/CreateUserReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/LoginReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/PasswordRecoveryReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/PasswordStatusReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/PreviousUsersReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/TermsAndConditinsReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/reducers/WorkflowReducer' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/adSpecific/PasswordStatusStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/ButtonStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/CenteredSpinnerStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/CheckboxStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/FormFieldStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/HeaderStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/InputStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/ListItemStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/LogoImageStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/ModalStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/common/ModalStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/styles/ScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/util/ASCIIUtil' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/util/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/common/util/PixelUtil' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/assets/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/AccountInfoComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/ChangePasswordModalComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/DeleteUserModal' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/EdgeLoginQrComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/FourDigitInputComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/ImageHeaderComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/LogoImageHeader' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/OtpHeroComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/PasswordStatusComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/abSpecific/UserListItem' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/ChangePasswordAppComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/ChangePinAppComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/BackgroundImage' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Button' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Card' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/CardSection' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Checkbox' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/CustomModal' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/DropDownList' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/DropDownPicker' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/DropInput' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/FormField' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/FormFieldWithDropComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Gradient' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Header' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/HeaderBackButton' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Icon' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/IconButton' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/ImageButton' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Input' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/ListItems/TextRowComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Modal' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/OverlayBox' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/SafeAreaView' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/SafeAreaViewGradient' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/ScrollingList' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/Spinner' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/StaticModal' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/TextAndIconButton' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/common/WarningBox' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/ChangePasswordScreen' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/ChangePinScreen' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/ChooseTestAppScreen' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/LoginScreen' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/PasswordRecoveryScreen' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/TouchID' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/LogInAppComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/materialWrappers/AutoCompleteInput' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/materialWrappers/indexMaterial' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/materialWrappers/Input' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/materialWrappers/PasswordComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/PasswordRecoveryAppComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPasswordScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPinScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/LoginWithRecoveryQuestionsScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/OtpErrorScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/RecoverPasswordScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/LandingScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/LoadingScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/LoginUsernamePasswordScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/CreatingAccountWaitScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountPasswordScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountReviewScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountUsernameScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWalletCreationScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWelcomeScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/SetAccountPinScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/TermsAndConditionsScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/PermissionScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/components/screens/TemplateScreenComponent' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/AccountInfoConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/ChangePasswordModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/ChangePinModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/CreateFourDigitPinConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/DeleteUserConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/DisableOtpModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/EmailAppFailedModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/ForgotPasswordModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/FourDigitInputConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/OtpAuthCodeModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/PasswordStatusConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/SaveRecoveryTokenModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/SetRecoveryUsernameModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/SkipModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/ChangePasswordAppConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/ChangePinConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/EdgeLoginQrConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnectorChangeApps' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnectorOtp' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderRecoverPasswordLogin' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/OtpBackupKeyConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/PasswordConfirmConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/PasswordConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/RecoverPasswordUsernameModalConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/UsernameConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/UsernameDropConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/LogInAppConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/PasswordRecoveryConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ChangeAccountPasswordScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ChangeAccountPinScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ForgotPasswordChangePasswordConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ForgotPinChangePinConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/LoginWithRecoveryQuestionsSceenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/OtpErrorScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/RecoverPasswordScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/LandingScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/LoadingScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/LogInUsernamePasswordScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/CreatingAccountWaitScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountPasswordScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountReviewScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountUsernameScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWalletCreationScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWelcomeScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/SetAccountPinScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/TermsAndConditionsScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/PermissionScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/PinLoginScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/connectors/screens/TemplateScreenConnector' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/constants/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/constants/LayoutConstants' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/keychain' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/components/EdgeLoginQrStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/components/FourDotInputStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/components/LogoHeaderStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/index' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/CreatingAccountWaitScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/LandingScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/LoginPasswordScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/LoginWithRecoveryStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountPasswordScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountReviewScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountUsernameScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountWelcomeScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/OtpErrorScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/RecoverPasswordSceneStyles' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/SetAccountPinScreenStyle' {
  declare module.exports: any;
}

declare module 'edge-login-ui-rn/src/native/styles/screens/TermsAndConditionsScreenStyle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'edge-login-ui-rn/src/common/actions/ChangePasswordPinActions.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/ChangePasswordPinActions'>;
}
declare module 'edge-login-ui-rn/src/common/actions/CreateAccountActions.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/CreateAccountActions'>;
}
declare module 'edge-login-ui-rn/src/common/actions/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/index'>;
}
declare module 'edge-login-ui-rn/src/common/actions/LoginAction.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/LoginAction'>;
}
declare module 'edge-login-ui-rn/src/common/actions/PasswordRecoveryActions.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/PasswordRecoveryActions'>;
}
declare module 'edge-login-ui-rn/src/common/actions/PreviousUsersActions.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/PreviousUsersActions'>;
}
declare module 'edge-login-ui-rn/src/common/actions/UserActions.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/UserActions'>;
}
declare module 'edge-login-ui-rn/src/common/actions/WorkflowActions.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/actions/WorkflowActions'>;
}
declare module 'edge-login-ui-rn/src/common/constants/Colors.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/Colors'>;
}
declare module 'edge-login-ui-rn/src/common/constants/ErrorConstants.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/ErrorConstants'>;
}
declare module 'edge-login-ui-rn/src/common/constants/Fonts.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/Fonts'>;
}
declare module 'edge-login-ui-rn/src/common/constants/IconConstants.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/IconConstants'>;
}
declare module 'edge-login-ui-rn/src/common/constants/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/index'>;
}
declare module 'edge-login-ui-rn/src/common/constants/OtpConstants.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/OtpConstants'>;
}
declare module 'edge-login-ui-rn/src/common/constants/Theme.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/Theme'>;
}
declare module 'edge-login-ui-rn/src/common/constants/ToLocalizeConstants.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/constants/ToLocalizeConstants'>;
}
declare module 'edge-login-ui-rn/src/common/dataHelpers/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/dataHelpers/index'>;
}
declare module 'edge-login-ui-rn/src/common/dataHelpers/PasswordEvalHelper.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/dataHelpers/PasswordEvalHelper'>;
}
declare module 'edge-login-ui-rn/src/common/locale/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/locale/index'>;
}
declare module 'edge-login-ui-rn/src/common/locale/translations.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/locale/translations'>;
}
declare module 'edge-login-ui-rn/src/common/locale/traslationKeys.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/locale/traslationKeys'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/CreateUserReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/CreateUserReducer'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/index'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/LoginReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/LoginReducer'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/PasswordRecoveryReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/PasswordRecoveryReducer'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/PasswordStatusReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/PasswordStatusReducer'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/PreviousUsersReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/PreviousUsersReducer'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/TermsAndConditinsReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/TermsAndConditinsReducer'>;
}
declare module 'edge-login-ui-rn/src/common/reducers/WorkflowReducer.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/reducers/WorkflowReducer'>;
}
declare module 'edge-login-ui-rn/src/common/styles/adSpecific/PasswordStatusStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/adSpecific/PasswordStatusStyle'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/ButtonStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/ButtonStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/CenteredSpinnerStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/CenteredSpinnerStyle'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/CheckboxStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/CheckboxStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/FormFieldStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/FormFieldStyle'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/HeaderStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/HeaderStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/InputStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/InputStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/ListItemStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/ListItemStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/LogoImageStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/LogoImageStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/ModalStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/ModalStyle'>;
}
declare module 'edge-login-ui-rn/src/common/styles/common/ModalStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/common/ModalStyles'>;
}
declare module 'edge-login-ui-rn/src/common/styles/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/index'>;
}
declare module 'edge-login-ui-rn/src/common/styles/ScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/styles/ScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/common/util/ASCIIUtil.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/util/ASCIIUtil'>;
}
declare module 'edge-login-ui-rn/src/common/util/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/util/index'>;
}
declare module 'edge-login-ui-rn/src/common/util/PixelUtil.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/common/util/PixelUtil'>;
}
declare module 'edge-login-ui-rn/src/native/assets/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/assets/index'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/AccountInfoComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/AccountInfoComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/ChangePasswordModalComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/ChangePasswordModalComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/DeleteUserModal.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/DeleteUserModal'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/EdgeLoginQrComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/EdgeLoginQrComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/FourDigitInputComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/FourDigitInputComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/ImageHeaderComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/ImageHeaderComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/index'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/LogoImageHeader.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/LogoImageHeader'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/OtpHeroComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/OtpHeroComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/PasswordStatusComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/PasswordStatusComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/abSpecific/UserListItem.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/abSpecific/UserListItem'>;
}
declare module 'edge-login-ui-rn/src/native/components/ChangePasswordAppComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/ChangePasswordAppComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/ChangePinAppComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/ChangePinAppComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/BackgroundImage.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/BackgroundImage'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Button.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Button'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Card.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Card'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/CardSection.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/CardSection'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Checkbox.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Checkbox'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/CustomModal.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/CustomModal'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/DropDownList.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/DropDownList'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/DropDownPicker.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/DropDownPicker'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/DropInput.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/DropInput'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/FormField.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/FormField'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/FormFieldWithDropComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/FormFieldWithDropComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Gradient.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Gradient'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Header.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Header'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/HeaderBackButton.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/HeaderBackButton'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Icon.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Icon'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/IconButton.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/IconButton'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/ImageButton.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/ImageButton'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/index'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Input.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Input'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/ListItems/TextRowComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/ListItems/TextRowComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Modal.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Modal'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/OverlayBox.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/OverlayBox'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/SafeAreaView.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/SafeAreaView'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/SafeAreaViewGradient.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/SafeAreaViewGradient'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/ScrollingList.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/ScrollingList'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/Spinner.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/Spinner'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/StaticModal.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/StaticModal'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/TextAndIconButton.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/TextAndIconButton'>;
}
declare module 'edge-login-ui-rn/src/native/components/common/WarningBox.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/common/WarningBox'>;
}
declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/ChangePasswordScreen.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/exportAPIComponents/ChangePasswordScreen'>;
}
declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/ChangePinScreen.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/exportAPIComponents/ChangePinScreen'>;
}
declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/ChooseTestAppScreen.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/exportAPIComponents/ChooseTestAppScreen'>;
}
declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/LoginScreen.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/exportAPIComponents/LoginScreen'>;
}
declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/PasswordRecoveryScreen.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/exportAPIComponents/PasswordRecoveryScreen'>;
}
declare module 'edge-login-ui-rn/src/native/components/exportAPIComponents/TouchID.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/exportAPIComponents/TouchID'>;
}
declare module 'edge-login-ui-rn/src/native/components/LogInAppComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/LogInAppComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/materialWrappers/AutoCompleteInput.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/materialWrappers/AutoCompleteInput'>;
}
declare module 'edge-login-ui-rn/src/native/components/materialWrappers/indexMaterial.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/materialWrappers/indexMaterial'>;
}
declare module 'edge-login-ui-rn/src/native/components/materialWrappers/Input.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/materialWrappers/Input'>;
}
declare module 'edge-login-ui-rn/src/native/components/materialWrappers/PasswordComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/materialWrappers/PasswordComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/PasswordRecoveryAppComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/PasswordRecoveryAppComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPasswordScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPasswordScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPinScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPinScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/LoginWithRecoveryQuestionsScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/existingAccout/LoginWithRecoveryQuestionsScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/OtpErrorScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/existingAccout/OtpErrorScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/existingAccout/RecoverPasswordScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/existingAccout/RecoverPasswordScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/LandingScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/LandingScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/LoadingScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/LoadingScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/LoginUsernamePasswordScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/LoginUsernamePasswordScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/CreatingAccountWaitScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/CreatingAccountWaitScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountPasswordScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountPasswordScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountReviewScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountReviewScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountUsernameScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountUsernameScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWalletCreationScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWalletCreationScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWelcomeScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWelcomeScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/SetAccountPinScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/SetAccountPinScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/newAccount/TermsAndConditionsScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/newAccount/TermsAndConditionsScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/PermissionScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/PermissionScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/components/screens/TemplateScreenComponent.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/components/screens/TemplateScreenComponent'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/AccountInfoConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/AccountInfoConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/ChangePasswordModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/ChangePasswordModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/ChangePinModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/ChangePinModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/CreateFourDigitPinConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/CreateFourDigitPinConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/DeleteUserConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/DeleteUserConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/DisableOtpModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/DisableOtpModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/EmailAppFailedModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/EmailAppFailedModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/ForgotPasswordModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/ForgotPasswordModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/FourDigitInputConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/FourDigitInputConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/OtpAuthCodeModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/OtpAuthCodeModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/PasswordStatusConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/PasswordStatusConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/SaveRecoveryTokenModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/SaveRecoveryTokenModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/SetRecoveryUsernameModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/SetRecoveryUsernameModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/abSpecific/SkipModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/abSpecific/SkipModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/ChangePasswordAppConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/ChangePasswordAppConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/ChangePinConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/ChangePinConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/EdgeLoginQrConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/EdgeLoginQrConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnectorChangeApps.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnectorChangeApps'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnectorOtp.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderConnectorOtp'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderRecoverPasswordLogin.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderRecoverPasswordLogin'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/OtpBackupKeyConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/OtpBackupKeyConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/PasswordConfirmConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/PasswordConfirmConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/PasswordConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/PasswordConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/RecoverPasswordUsernameModalConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/RecoverPasswordUsernameModalConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/UsernameConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/UsernameConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/componentConnectors/UsernameDropConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/componentConnectors/UsernameDropConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/LogInAppConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/LogInAppConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/PasswordRecoveryConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/PasswordRecoveryConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ChangeAccountPasswordScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ChangeAccountPasswordScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ChangeAccountPinScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ChangeAccountPinScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ForgotPasswordChangePasswordConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ForgotPasswordChangePasswordConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ForgotPinChangePinConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/ForgotPinChangePinConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/LoginWithRecoveryQuestionsSceenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/LoginWithRecoveryQuestionsSceenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/OtpErrorScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/OtpErrorScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/existingAccount/RecoverPasswordScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/existingAccount/RecoverPasswordScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/index'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/LandingScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/LandingScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/LoadingScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/LoadingScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/LogInUsernamePasswordScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/LogInUsernamePasswordScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/CreatingAccountWaitScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/CreatingAccountWaitScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountPasswordScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountPasswordScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountReviewScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountReviewScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountUsernameScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountUsernameScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWalletCreationScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWalletCreationScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWelcomeScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWelcomeScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/SetAccountPinScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/SetAccountPinScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/newAccount/TermsAndConditionsScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/newAccount/TermsAndConditionsScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/PermissionScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/PermissionScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/PinLoginScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/PinLoginScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/connectors/screens/TemplateScreenConnector.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/connectors/screens/TemplateScreenConnector'>;
}
declare module 'edge-login-ui-rn/src/native/constants/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/constants/index'>;
}
declare module 'edge-login-ui-rn/src/native/constants/LayoutConstants.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/constants/LayoutConstants'>;
}
declare module 'edge-login-ui-rn/src/native/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/index'>;
}
declare module 'edge-login-ui-rn/src/native/keychain.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/keychain'>;
}
declare module 'edge-login-ui-rn/src/native/styles/components/EdgeLoginQrStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/components/EdgeLoginQrStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/components/FourDotInputStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/components/FourDotInputStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/components/LogoHeaderStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/components/LogoHeaderStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/index.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/index'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/CreatingAccountWaitScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/CreatingAccountWaitScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/LandingScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/LandingScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/LoginPasswordScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/LoginPasswordScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/LoginWithRecoveryStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/LoginWithRecoveryStyles'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountPasswordScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/NewAccountPasswordScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountReviewScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/NewAccountReviewScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountUsernameScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/NewAccountUsernameScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/NewAccountWelcomeScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/NewAccountWelcomeScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/OtpErrorScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/OtpErrorScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/RecoverPasswordSceneStyles.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/RecoverPasswordSceneStyles'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/SetAccountPinScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/SetAccountPinScreenStyle'>;
}
declare module 'edge-login-ui-rn/src/native/styles/screens/TermsAndConditionsScreenStyle.js' {
  declare module.exports: $Exports<'edge-login-ui-rn/src/native/styles/screens/TermsAndConditionsScreenStyle'>;
}
