// flow-typed signature: 022fa2368b645c319829b9f544489925
// flow-typed version: <<STUB>>/edge-exchange-plugins_v^0.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'edge-exchange-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'edge-exchange-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'edge-exchange-plugins/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'edge-exchange-plugins/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'edge-exchange-plugins/lib/index.cjs.js' {
  declare module.exports: $Exports<'edge-exchange-plugins/lib/index.cjs'>;
}
declare module 'edge-exchange-plugins/lib/index.js' {
  declare module.exports: $Exports<'edge-exchange-plugins/lib/index'>;
}
