// flow-typed signature: 3532a47a9dd948b8047c425262aaab1a
// flow-typed version: <<STUB>>/https-browserify_v0.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'https-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'https-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'https-browserify/index' {
  declare module.exports: $Exports<'https-browserify'>;
}
declare module 'https-browserify/index.js' {
  declare module.exports: $Exports<'https-browserify'>;
}
