// flow-typed signature: 8943ea13661aaf899d01be4fb71d751c
// flow-typed version: <<STUB>>/inherits_v^2.0.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inherits'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inherits' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inherits/inherits_browser' {
  declare module.exports: any;
}

declare module 'inherits/inherits' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inherits/inherits_browser.js' {
  declare module.exports: $Exports<'inherits/inherits_browser'>;
}
declare module 'inherits/inherits.js' {
  declare module.exports: $Exports<'inherits/inherits'>;
}
