// flow-typed signature: 192a3101098b9e6e935335233509279d
// flow-typed version: <<STUB>>/os-browserify_v^0.1.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'os-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'os-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'os-browserify/browser' {
  declare module.exports: any;
}

declare module 'os-browserify/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'os-browserify/browser.js' {
  declare module.exports: $Exports<'os-browserify/browser'>;
}
declare module 'os-browserify/main.js' {
  declare module.exports: $Exports<'os-browserify/main'>;
}
