// flow-typed signature: 543efd6a6dc2a2e52783daa8561c9176
// flow-typed version: <<STUB>>/process_v^0.11.10/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'process'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'process' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'process/browser' {
  declare module.exports: any;
}

declare module 'process/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'process/browser.js' {
  declare module.exports: $Exports<'process/browser'>;
}
declare module 'process/index' {
  declare module.exports: $Exports<'process'>;
}
declare module 'process/index.js' {
  declare module.exports: $Exports<'process'>;
}
declare module 'process/test.js' {
  declare module.exports: $Exports<'process/test'>;
}
