// flow-typed signature: daf0541952f34a25b171f626f0419bc6
// flow-typed version: <<STUB>>/querystring-es3_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystring-es3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystring-es3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'querystring-es3/decode' {
  declare module.exports: any;
}

declare module 'querystring-es3/encode' {
  declare module.exports: any;
}

declare module 'querystring-es3/test/common-index' {
  declare module.exports: any;
}

declare module 'querystring-es3/test/index' {
  declare module.exports: any;
}

declare module 'querystring-es3/test/tap-index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'querystring-es3/decode.js' {
  declare module.exports: $Exports<'querystring-es3/decode'>;
}
declare module 'querystring-es3/encode.js' {
  declare module.exports: $Exports<'querystring-es3/encode'>;
}
declare module 'querystring-es3/index' {
  declare module.exports: $Exports<'querystring-es3'>;
}
declare module 'querystring-es3/index.js' {
  declare module.exports: $Exports<'querystring-es3'>;
}
declare module 'querystring-es3/test/common-index.js' {
  declare module.exports: $Exports<'querystring-es3/test/common-index'>;
}
declare module 'querystring-es3/test/index.js' {
  declare module.exports: $Exports<'querystring-es3/test/index'>;
}
declare module 'querystring-es3/test/tap-index.js' {
  declare module.exports: $Exports<'querystring-es3/test/tap-index'>;
}
