// flow-typed signature: fa6b0f3e58ba387bdbf7be93a1e02040
// flow-typed version: <<STUB>>/react-native-locale_v^0.0.17/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-locale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-locale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-locale/index.android' {
  declare module.exports: any;
}

declare module 'react-native-locale/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-locale/LocaleBaseClass' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-locale/index.android.js' {
  declare module.exports: $Exports<'react-native-locale/index.android'>;
}
declare module 'react-native-locale/index.ios.js' {
  declare module.exports: $Exports<'react-native-locale/index.ios'>;
}
declare module 'react-native-locale/LocaleBaseClass.js' {
  declare module.exports: $Exports<'react-native-locale/LocaleBaseClass'>;
}
