// flow-typed signature: a3b7678708b9587d96f312c32a5b77b8
// flow-typed version: <<STUB>>/react-native-sortable-list_v0.0.16/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sortable-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sortable-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sortable-list/src/Row' {
  declare module.exports: any;
}

declare module 'react-native-sortable-list/src/SortableList' {
  declare module.exports: any;
}

declare module 'react-native-sortable-list/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-sortable-list/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-native-sortable-list/src/utils/swapArrayElements' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sortable-list/index' {
  declare module.exports: $Exports<'react-native-sortable-list'>;
}
declare module 'react-native-sortable-list/index.js' {
  declare module.exports: $Exports<'react-native-sortable-list'>;
}
declare module 'react-native-sortable-list/src/Row.js' {
  declare module.exports: $Exports<'react-native-sortable-list/src/Row'>;
}
declare module 'react-native-sortable-list/src/SortableList.js' {
  declare module.exports: $Exports<'react-native-sortable-list/src/SortableList'>;
}
declare module 'react-native-sortable-list/src/utils/index.js' {
  declare module.exports: $Exports<'react-native-sortable-list/src/utils/index'>;
}
declare module 'react-native-sortable-list/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-native-sortable-list/src/utils/shallowEqual'>;
}
declare module 'react-native-sortable-list/src/utils/swapArrayElements.js' {
  declare module.exports: $Exports<'react-native-sortable-list/src/utils/swapArrayElements'>;
}
