// flow-typed signature: d937a8e78ab3b34d08ba8fb571e09927
// flow-typed version: <<STUB>>/react-native-modal_v^2.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal/src/animations' {
  declare module.exports: any;
}

declare module 'react-native-modal/src/index' {
  declare module.exports: any;
}

declare module 'react-native-modal/src/index.style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal/src/animations.js' {
  declare module.exports: $Exports<'react-native-modal/src/animations'>;
}
declare module 'react-native-modal/src/index.js' {
  declare module.exports: $Exports<'react-native-modal/src/index'>;
}
declare module 'react-native-modal/src/index.style.js' {
  declare module.exports: $Exports<'react-native-modal/src/index.style'>;
}
