// flow-typed signature: 273ceb7d1856a16a6fc3f71f06b98933
// flow-typed version: <<STUB>>/react-native-udp_v^2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-udp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-udp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-udp/examples/rctsockets/index.android' {
  declare module.exports: any;
}

declare module 'react-native-udp/examples/rctsockets/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-udp/examples/rctsockets/test' {
  declare module.exports: any;
}

declare module 'react-native-udp/UdpSocket' {
  declare module.exports: any;
}

declare module 'react-native-udp/UdpSockets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-udp/examples/rctsockets/index.android.js' {
  declare module.exports: $Exports<'react-native-udp/examples/rctsockets/index.android'>;
}
declare module 'react-native-udp/examples/rctsockets/index.ios.js' {
  declare module.exports: $Exports<'react-native-udp/examples/rctsockets/index.ios'>;
}
declare module 'react-native-udp/examples/rctsockets/test.js' {
  declare module.exports: $Exports<'react-native-udp/examples/rctsockets/test'>;
}
declare module 'react-native-udp/UdpSocket.js' {
  declare module.exports: $Exports<'react-native-udp/UdpSocket'>;
}
declare module 'react-native-udp/UdpSockets.js' {
  declare module.exports: $Exports<'react-native-udp/UdpSockets'>;
}
