// flow-typed signature: 0571a5556cfcf4d102139d4c273df124
// flow-typed version: <<STUB>>/react-native-permissions_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-permissions/index.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-permissions/index.android.js' {
  declare module.exports: $Exports<'react-native-permissions/index.android'>;
}
declare module 'react-native-permissions/index.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/index.ios'>;
}
