// flow-typed signature: a1bbcaa761f5d90efbdaeada21ef1b9f
// flow-typed version: <<STUB>>/react-native-background-task_v0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-background-task'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-background-task' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-background-task/js/contants' {
  declare module.exports: any;
}

declare module 'react-native-background-task/js/index.android' {
  declare module.exports: any;
}

declare module 'react-native-background-task/js/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-background-task/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-background-task/js/contants.js' {
  declare module.exports: $Exports<'react-native-background-task/js/contants'>;
}
declare module 'react-native-background-task/js/index.android.js' {
  declare module.exports: $Exports<'react-native-background-task/js/index.android'>;
}
declare module 'react-native-background-task/js/index.ios.js' {
  declare module.exports: $Exports<'react-native-background-task/js/index.ios'>;
}
declare module 'react-native-background-task/types.js' {
  declare module.exports: $Exports<'react-native-background-task/types'>;
}
