// flow-typed signature: 5836a58496ea5b733152b6ab100e08c7
// flow-typed version: <<STUB>>/react-native-text_v0.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-text/index' {
  declare module.exports: $Exports<'react-native-text'>;
}
declare module 'react-native-text/index.js' {
  declare module.exports: $Exports<'react-native-text'>;
}
