// flow-typed signature: 9a692cc10f28a581fc43562518c49d88
// flow-typed version: <<STUB>>/react-native-local-notification_v3.0.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-local-notification'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-local-notification' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-local-notification/Example/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-local-notification/Example/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-local-notification/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-local-notification/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-local-notification/Example/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-local-notification/Example/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-local-notification/Example/__tests__/index.android'>;
}
declare module 'react-native-local-notification/Example/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-local-notification/Example/__tests__/index.ios'>;
}
declare module 'react-native-local-notification/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-local-notification/Example/index.android'>;
}
declare module 'react-native-local-notification/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-local-notification/Example/index.ios'>;
}
declare module 'react-native-local-notification/Example/src/main.js' {
  declare module.exports: $Exports<'react-native-local-notification/Example/src/main'>;
}
declare module 'react-native-local-notification/index' {
  declare module.exports: $Exports<'react-native-local-notification'>;
}
declare module 'react-native-local-notification/index.js' {
  declare module.exports: $Exports<'react-native-local-notification'>;
}
