// flow-typed signature: 6dabf68b2684627436cc5ad3b2fe0df1
// flow-typed version: <<STUB>>/react-native-crypto_v^2.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-crypto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-crypto/index' {
  declare module.exports: $Exports<'react-native-crypto'>;
}
declare module 'react-native-crypto/index.js' {
  declare module.exports: $Exports<'react-native-crypto'>;
}
