// flow-typed signature: af587113179ab56d39a18bbca7eff236
// flow-typed version: <<STUB>>/react-native-randombytes_v^2.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-randombytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-randombytes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-randombytes/index' {
  declare module.exports: $Exports<'react-native-randombytes'>;
}
declare module 'react-native-randombytes/index.js' {
  declare module.exports: $Exports<'react-native-randombytes'>;
}
