// flow-typed signature: 2c816e63d9391b4e116f6663712b4cf9
// flow-typed version: <<STUB>>/react-native-sortable-listview_v0.2.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sortable-listview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sortable-listview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sortable-listview/__tests__/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sortable-listview/__tests__/index.test.js' {
  declare module.exports: $Exports<'react-native-sortable-listview/__tests__/index.test'>;
}
declare module 'react-native-sortable-listview/index' {
  declare module.exports: $Exports<'react-native-sortable-listview'>;
}
declare module 'react-native-sortable-listview/index.js' {
  declare module.exports: $Exports<'react-native-sortable-listview'>;
}
