// flow-typed signature: bf8f324d917f5de1dc28814d51c57dcc
// flow-typed version: <<STUB>>/react-native-hockeyapp_v^0.5.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-hockeyapp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-hockeyapp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-hockeyapp/index' {
  declare module.exports: $Exports<'react-native-hockeyapp'>;
}
declare module 'react-native-hockeyapp/index.js' {
  declare module.exports: $Exports<'react-native-hockeyapp'>;
}
