// flow-typed signature: 5423f7b77e0f8a156c794afd2ac6494d
// flow-typed version: <<STUB>>/react-native-level-fs_v^3.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-level-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-level-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-level-fs/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-level-fs/example.js' {
  declare module.exports: $Exports<'react-native-level-fs/example'>;
}
declare module 'react-native-level-fs/index' {
  declare module.exports: $Exports<'react-native-level-fs'>;
}
declare module 'react-native-level-fs/index.js' {
  declare module.exports: $Exports<'react-native-level-fs'>;
}
