// flow-typed signature: 1ec600c2c2778d68af9ff0ac24dec3b7
// flow-typed version: <<STUB>>/react-native-flip-view_vgit://github.com/Airbitz/react-native-flip-view.git/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-flip-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-flip-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-flip-view/index' {
  declare module.exports: $Exports<'react-native-flip-view'>;
}
declare module 'react-native-flip-view/index.js' {
  declare module.exports: $Exports<'react-native-flip-view'>;
}
