// flow-typed signature: 7fea3f5117ef7b701207d9e8325568ee
// flow-typed version: <<STUB>>/react-native-share_v^1.0.20/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-share'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-share' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-share/components/Button' {
  declare module.exports: any;
}

declare module 'react-native-share/components/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-share/components/Sheet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-share/components/Button.js' {
  declare module.exports: $Exports<'react-native-share/components/Button'>;
}
declare module 'react-native-share/components/Overlay.js' {
  declare module.exports: $Exports<'react-native-share/components/Overlay'>;
}
declare module 'react-native-share/components/Sheet.js' {
  declare module.exports: $Exports<'react-native-share/components/Sheet'>;
}
declare module 'react-native-share/index' {
  declare module.exports: $Exports<'react-native-share'>;
}
declare module 'react-native-share/index.js' {
  declare module.exports: $Exports<'react-native-share'>;
}
