// flow-typed signature: 85400dc87e21fbd1fd65a690b738162d
// flow-typed version: <<STUB>>/react-native-qrcode_v^0.2.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-qrcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-qrcode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-qrcode/lib/Canvas' {
  declare module.exports: any;
}

declare module 'react-native-qrcode/lib/QRCode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-qrcode/index' {
  declare module.exports: $Exports<'react-native-qrcode'>;
}
declare module 'react-native-qrcode/index.js' {
  declare module.exports: $Exports<'react-native-qrcode'>;
}
declare module 'react-native-qrcode/lib/Canvas.js' {
  declare module.exports: $Exports<'react-native-qrcode/lib/Canvas'>;
}
declare module 'react-native-qrcode/lib/QRCode.js' {
  declare module.exports: $Exports<'react-native-qrcode/lib/QRCode'>;
}
