// flow-typed signature: cc7ac5f555e0d53fee3a912381fa8373
// flow-typed version: <<STUB>>/react-native-dropdown_vgit://github.com/g6ling/react-native-dropdown.git/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-dropdown/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-dropdown/lib/items' {
  declare module.exports: any;
}

declare module 'react-native-dropdown/lib/option' {
  declare module.exports: any;
}

declare module 'react-native-dropdown/lib/optionList' {
  declare module.exports: any;
}

declare module 'react-native-dropdown/lib/overlay' {
  declare module.exports: any;
}

declare module 'react-native-dropdown/lib/select' {
  declare module.exports: any;
}

declare module 'react-native-dropdown/lib/updatePosition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-dropdown/lib/index.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/index'>;
}
declare module 'react-native-dropdown/lib/items.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/items'>;
}
declare module 'react-native-dropdown/lib/option.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/option'>;
}
declare module 'react-native-dropdown/lib/optionList.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/optionList'>;
}
declare module 'react-native-dropdown/lib/overlay.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/overlay'>;
}
declare module 'react-native-dropdown/lib/select.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/select'>;
}
declare module 'react-native-dropdown/lib/updatePosition.js' {
  declare module.exports: $Exports<'react-native-dropdown/lib/updatePosition'>;
}
