// flow-typed signature: 510e633233e2e2594fc6451eb1605eac
// flow-typed version: <<STUB>>/react-native-animatable_v^1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-animatable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-animatable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-animatable/createAnimatableComponent' {
  declare module.exports: any;
}

declare module 'react-native-animatable/createAnimation' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/attention-seekers' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/bouncing-entrances' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/bouncing-exits' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/fading-entrances' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/fading-exits' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/flippers' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/index' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/lightspeed' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/sliding-entrances' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/sliding-exits' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/zooming-entrances' {
  declare module.exports: any;
}

declare module 'react-native-animatable/definitions/zooming-exits' {
  declare module.exports: any;
}

declare module 'react-native-animatable/easing' {
  declare module.exports: any;
}

declare module 'react-native-animatable/flattenStyle' {
  declare module.exports: any;
}

declare module 'react-native-animatable/getDefaultStyleValue' {
  declare module.exports: any;
}

declare module 'react-native-animatable/getStyleValues' {
  declare module.exports: any;
}

declare module 'react-native-animatable/registry' {
  declare module.exports: any;
}

declare module 'react-native-animatable/wrapStyleTransforms' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-animatable/createAnimatableComponent.js' {
  declare module.exports: $Exports<'react-native-animatable/createAnimatableComponent'>;
}
declare module 'react-native-animatable/createAnimation.js' {
  declare module.exports: $Exports<'react-native-animatable/createAnimation'>;
}
declare module 'react-native-animatable/definitions/attention-seekers.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/attention-seekers'>;
}
declare module 'react-native-animatable/definitions/bouncing-entrances.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/bouncing-entrances'>;
}
declare module 'react-native-animatable/definitions/bouncing-exits.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/bouncing-exits'>;
}
declare module 'react-native-animatable/definitions/fading-entrances.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/fading-entrances'>;
}
declare module 'react-native-animatable/definitions/fading-exits.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/fading-exits'>;
}
declare module 'react-native-animatable/definitions/flippers.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/flippers'>;
}
declare module 'react-native-animatable/definitions/index.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/index'>;
}
declare module 'react-native-animatable/definitions/lightspeed.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/lightspeed'>;
}
declare module 'react-native-animatable/definitions/sliding-entrances.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/sliding-entrances'>;
}
declare module 'react-native-animatable/definitions/sliding-exits.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/sliding-exits'>;
}
declare module 'react-native-animatable/definitions/zooming-entrances.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/zooming-entrances'>;
}
declare module 'react-native-animatable/definitions/zooming-exits.js' {
  declare module.exports: $Exports<'react-native-animatable/definitions/zooming-exits'>;
}
declare module 'react-native-animatable/easing.js' {
  declare module.exports: $Exports<'react-native-animatable/easing'>;
}
declare module 'react-native-animatable/flattenStyle.js' {
  declare module.exports: $Exports<'react-native-animatable/flattenStyle'>;
}
declare module 'react-native-animatable/getDefaultStyleValue.js' {
  declare module.exports: $Exports<'react-native-animatable/getDefaultStyleValue'>;
}
declare module 'react-native-animatable/getStyleValues.js' {
  declare module.exports: $Exports<'react-native-animatable/getStyleValues'>;
}
declare module 'react-native-animatable/index' {
  declare module.exports: $Exports<'react-native-animatable'>;
}
declare module 'react-native-animatable/index.js' {
  declare module.exports: $Exports<'react-native-animatable'>;
}
declare module 'react-native-animatable/registry.js' {
  declare module.exports: $Exports<'react-native-animatable/registry'>;
}
declare module 'react-native-animatable/wrapStyleTransforms.js' {
  declare module.exports: $Exports<'react-native-animatable/wrapStyleTransforms'>;
}
