// flow-typed signature: 792b2aab46fb5ea0bb5f31fb39bdeb55
// flow-typed version: <<STUB>>/react-native-background-fetch_v2.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-background-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-background-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-background-fetch/index.android' {
  declare module.exports: any;
}

declare module 'react-native-background-fetch/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-background-fetch/scripts/postlink' {
  declare module.exports: any;
}

declare module 'react-native-background-fetch/scripts/postunlink' {
  declare module.exports: any;
}

declare module 'react-native-background-fetch/scripts/xcode-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-background-fetch/index.android.js' {
  declare module.exports: $Exports<'react-native-background-fetch/index.android'>;
}
declare module 'react-native-background-fetch/index.ios.js' {
  declare module.exports: $Exports<'react-native-background-fetch/index.ios'>;
}
declare module 'react-native-background-fetch/scripts/postlink.js' {
  declare module.exports: $Exports<'react-native-background-fetch/scripts/postlink'>;
}
declare module 'react-native-background-fetch/scripts/postunlink.js' {
  declare module.exports: $Exports<'react-native-background-fetch/scripts/postunlink'>;
}
declare module 'react-native-background-fetch/scripts/xcode-helpers.js' {
  declare module.exports: $Exports<'react-native-background-fetch/scripts/xcode-helpers'>;
}
