// flow-typed signature: 0863f8425cb780fecaf3ecd491a3a40d
// flow-typed version: <<STUB>>/redux-immutable-state-invariant_v^1.2.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-immutable-state-invariant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-immutable-state-invariant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-immutable-state-invariant/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/dist/index' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/dist/isImmutable' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/dist/trackForMutations' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-immutable-state-invariant/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/coverage/lcov-report/prettify'>;
}
declare module 'redux-immutable-state-invariant/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/coverage/lcov-report/sorter'>;
}
declare module 'redux-immutable-state-invariant/dist/index.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/dist/index'>;
}
declare module 'redux-immutable-state-invariant/dist/isImmutable.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/dist/isImmutable'>;
}
declare module 'redux-immutable-state-invariant/dist/trackForMutations.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/dist/trackForMutations'>;
}
declare module 'redux-immutable-state-invariant/example/webpack.config.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/example/webpack.config'>;
}
