// flow-typed signature: 14deaac3551e8e3f498b142b39a13071
// flow-typed version: <<STUB>>/string_decoder_v^0.10.31/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string_decoder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string_decoder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string_decoder/index' {
  declare module.exports: $Exports<'string_decoder'>;
}
declare module 'string_decoder/index.js' {
  declare module.exports: $Exports<'string_decoder'>;
}
