// flow-typed signature: df1df788d46299a33ae63afb8156dbf6
// flow-typed version: <<STUB>>/timers-browserify_v^1.4.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timers-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timers-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timers-browserify/example/enroll/js/browserify' {
  declare module.exports: any;
}

declare module 'timers-browserify/example/enroll/js/main' {
  declare module.exports: any;
}

declare module 'timers-browserify/example/enroll/server' {
  declare module.exports: any;
}

declare module 'timers-browserify/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timers-browserify/example/enroll/js/browserify.js' {
  declare module.exports: $Exports<'timers-browserify/example/enroll/js/browserify'>;
}
declare module 'timers-browserify/example/enroll/js/main.js' {
  declare module.exports: $Exports<'timers-browserify/example/enroll/js/main'>;
}
declare module 'timers-browserify/example/enroll/server.js' {
  declare module.exports: $Exports<'timers-browserify/example/enroll/server'>;
}
declare module 'timers-browserify/main.js' {
  declare module.exports: $Exports<'timers-browserify/main'>;
}
