// flow-typed signature: 0ff09dd3c5cedf76cf60508ee5cc83d9
// flow-typed version: <<STUB>>/updot_v^1.1.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'updot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'updot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'updot/index' {
  declare module.exports: $Exports<'updot'>;
}
declare module 'updot/index.js' {
  declare module.exports: $Exports<'updot'>;
}
