// flow-typed signature: fdd114810379f8397cd9b01db94f9d30
// flow-typed version: <<STUB>>/vm-browserify_v0.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vm-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vm-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vm-browserify/example/run/bundle' {
  declare module.exports: any;
}

declare module 'vm-browserify/example/run/entry' {
  declare module.exports: any;
}

declare module 'vm-browserify/example/run/server' {
  declare module.exports: any;
}

declare module 'vm-browserify/test/vm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vm-browserify/example/run/bundle.js' {
  declare module.exports: $Exports<'vm-browserify/example/run/bundle'>;
}
declare module 'vm-browserify/example/run/entry.js' {
  declare module.exports: $Exports<'vm-browserify/example/run/entry'>;
}
declare module 'vm-browserify/example/run/server.js' {
  declare module.exports: $Exports<'vm-browserify/example/run/server'>;
}
declare module 'vm-browserify/index' {
  declare module.exports: $Exports<'vm-browserify'>;
}
declare module 'vm-browserify/index.js' {
  declare module.exports: $Exports<'vm-browserify'>;
}
declare module 'vm-browserify/test/vm.js' {
  declare module.exports: $Exports<'vm-browserify/test/vm'>;
}
