// @flow

import { type CountryData } from '../types/types.js'
import { imageServerUrl } from './WalletAndCurrencyConstants.js'

export const FLAG_LOGO_URL = `${imageServerUrl}/country-logos`

export const COUNTRY_CODES: CountryData[] = [
  { name: 'Afghanistan', 'alpha-2': 'AF', fiat: '' },
  { name: 'Åland Islands', filename: 'aland-islands', 'alpha-2': 'AX' },
  { name: 'Albania', 'alpha-2': 'AL' },
  { name: 'Algeria', 'alpha-2': 'DZ' },
  { name: 'American Samoa', 'alpha-2': 'AS' },
  { name: 'Andorra', 'alpha-2': 'AD' },
  { name: 'Angola', 'alpha-2': 'AO' },
  { name: 'Anguilla', 'alpha-2': 'AI' },
  { name: 'Antigua and Barbuda', filename: 'antigua-and-barbuda', 'alpha-2': 'AG' },
  { name: 'Argentina', 'alpha-2': 'AR' },
  { name: 'Armenia', 'alpha-2': 'AM' },
  { name: 'Aruba', 'alpha-2': 'AW' },
  { name: 'Australia', 'alpha-2': 'AU' },
  { name: 'Austria', 'alpha-2': 'AT' },
  { name: 'Azerbaijan', 'alpha-2': 'AZ' },
  { name: 'Bahamas', 'alpha-2': 'BS' },
  { name: 'Bahrain', 'alpha-2': 'BH' },
  { name: 'Bangladesh', 'alpha-2': 'BD' },
  { name: 'Barbados', 'alpha-2': 'BB' },
  { name: 'Belarus', 'alpha-2': 'BY' },
  { name: 'Belgium', 'alpha-2': 'BE' },
  { name: 'Belize', 'alpha-2': 'BZ' },
  { name: 'Benin', 'alpha-2': 'BJ' },
  { name: 'Bermuda', 'alpha-2': 'BM' },
  { name: 'Bhutan', 'alpha-2': 'BT' },
  { name: 'Bolivia (Plurinational State of)', filename: 'bolivia', 'alpha-2': 'BO' },
  { name: 'Bonaire, Sint Eustatius and Saba', filename: 'bonaire', 'alpha-2': 'BQ' },
  { name: 'Bosnia and Herzegovina', filename: 'bosnia-and-herzegovina', 'alpha-2': 'BA' },
  { name: 'Botswana', 'alpha-2': 'BW' },
  { name: 'Brazil', 'alpha-2': 'BR' },
  { name: 'British Indian Ocean Territory', filename: 'british-indian-ocean-territory', 'alpha-2': 'IO' },
  { name: 'Brunei Darussalam', filename: 'brunei', 'alpha-2': 'BN' },
  { name: 'Bulgaria', 'alpha-2': 'BG' },
  { name: 'Burkina Faso', 'alpha-2': 'BF' },
  { name: 'Burundi', 'alpha-2': 'BI' },
  { name: 'Cabo Verde', filename: 'cape-verde', 'alpha-2': 'CV' },
  { name: 'Cambodia', 'alpha-2': 'KH' },
  { name: 'Cameroon', 'alpha-2': 'CM' },
  { name: 'Canada', 'alpha-2': 'CA' },
  { name: 'Cayman Islands', 'alpha-2': 'KY' },
  { name: 'Central African Republic', filename: 'central-african-republic', 'alpha-2': 'CF' },
  { name: 'Chad', 'alpha-2': 'TD' },
  { name: 'Chile', 'alpha-2': 'CL' },
  { name: 'China', 'alpha-2': 'CN' },
  { name: 'Christmas Island', 'alpha-2': 'CX' },
  { name: 'Cocos (Keeling) Islands', filename: 'cocos-island', 'alpha-2': 'CC' },
  { name: 'Colombia', 'alpha-2': 'CO' },
  { name: 'Comoros', 'alpha-2': 'KM' },
  { name: 'Congo', 'alpha-2': 'CG' },
  { name: 'Congo, Democratic Republic of the', filename: 'democratic-republic-of-congo', 'alpha-2': 'CD' },
  { name: 'Cook Islands', 'alpha-2': 'CK' },
  { name: 'Costa Rica', 'alpha-2': 'CR' },
  { name: "Côte d'Ivoire", filename: 'ivory-coast', 'alpha-2': 'CI' },
  { name: 'Croatia', 'alpha-2': 'HR' },
  { name: 'Cuba', 'alpha-2': 'CU' },
  { name: 'Curaçao', filename: 'curacao', 'alpha-2': 'CW' },
  { name: 'Cyprus', 'alpha-2': 'CY' },
  { name: 'Czechia', filename: 'czech-republic', 'alpha-2': 'CZ' },
  { name: 'Denmark', 'alpha-2': 'DK' },
  { name: 'Djibouti', 'alpha-2': 'DJ' },
  { name: 'Dominica', 'alpha-2': 'DM' },
  { name: 'Dominican Republic', 'alpha-2': 'DO' },
  { name: 'Ecuador', 'alpha-2': 'EC' },
  { name: 'Egypt', 'alpha-2': 'EG' },
  { name: 'El Salvador', filename: 'salvador', 'alpha-2': 'SV' },
  { name: 'Equatorial Guinea', 'alpha-2': 'GQ' },
  { name: 'Eritrea', 'alpha-2': 'ER' },
  { name: 'Estonia', 'alpha-2': 'EE' },
  { name: 'Eswatini', 'alpha-2': 'SZ' },
  { name: 'Ethiopia', 'alpha-2': 'ET' },
  { name: 'Falkland Islands (Malvinas)', filename: 'falkland-islands', 'alpha-2': 'FK' },
  { name: 'Faroe Islands', 'alpha-2': 'FO' },
  { name: 'Fiji', 'alpha-2': 'FJ' },
  { name: 'Finland', 'alpha-2': 'FI' },
  { name: 'France', 'alpha-2': 'FR' },
  { name: 'French Guiana', filename: 'guyana', 'alpha-2': 'GF' },
  { name: 'French Polynesia', 'alpha-2': 'PF' },
  { name: 'Gabon', 'alpha-2': 'GA' },
  { name: 'Gambia', 'alpha-2': 'GM' },
  { name: 'Georgia', 'alpha-2': 'GE' },
  { name: 'Germany', 'alpha-2': 'DE' },
  { name: 'Ghana', 'alpha-2': 'GH' },
  { name: 'Gibraltar', 'alpha-2': 'GI' },
  { name: 'Greece', 'alpha-2': 'GR' },
  { name: 'Greenland', 'alpha-2': 'GL' },
  { name: 'Grenada', 'alpha-2': 'GD' },
  { name: 'Guam', 'alpha-2': 'GU' },
  { name: 'Guatemala', 'alpha-2': 'GT' },
  { name: 'Guernsey', 'alpha-2': 'GG' },
  { name: 'Guinea', 'alpha-2': 'GN' },
  { name: 'Guinea-Bissau', 'alpha-2': 'GW' },
  { name: 'Guyana', 'alpha-2': 'GY' },
  { name: 'Haiti', 'alpha-2': 'HT' },
  { name: 'Holy See', filename: 'vatican-city', 'alpha-2': 'VA' },
  { name: 'Honduras', 'alpha-2': 'HN' },
  { name: 'Hong Kong', 'alpha-2': 'HK' },
  { name: 'Hungary', 'alpha-2': 'HU' },
  { name: 'Iceland', 'alpha-2': 'IS' },
  { name: 'India', 'alpha-2': 'IN' },
  { name: 'Indonesia', 'alpha-2': 'ID' },
  { name: 'Iran (Islamic Republic of)', filename: 'iran', 'alpha-2': 'IR' },
  { name: 'Iraq', 'alpha-2': 'IQ' },
  { name: 'Ireland', 'alpha-2': 'IE' },
  { name: 'Isle of Man', filename: 'isle-of-man', 'alpha-2': 'IM' },
  { name: 'Israel', 'alpha-2': 'IL' },
  { name: 'Italy', 'alpha-2': 'IT' },
  { name: 'Jamaica', 'alpha-2': 'JM' },
  { name: 'Japan', 'alpha-2': 'JP' },
  { name: 'Jersey', 'alpha-2': 'JE' },
  { name: 'Jordan', 'alpha-2': 'JO' },
  { name: 'Kazakhstan', 'alpha-2': 'KZ' },
  { name: 'Kenya', 'alpha-2': 'KE' },
  { name: 'Kiribati', 'alpha-2': 'KI' },
  { name: "Korea (Democratic People's Republic of)", filename: 'north-korea', 'alpha-2': 'KP' },
  { name: 'Korea, Republic of', filename: 'south-korea', 'alpha-2': 'KR' },
  { name: 'Kuwait', 'alpha-2': 'KW' },
  { name: 'Kyrgyzstan', 'alpha-2': 'KG' },
  { name: "Lao People's Democratic Republic", filename: 'laos', 'alpha-2': 'LA' },
  { name: 'Latvia', 'alpha-2': 'LV' },
  { name: 'Lebanon', 'alpha-2': 'LB' },
  { name: 'Lesotho', 'alpha-2': 'LS' },
  { name: 'Liberia', 'alpha-2': 'LR' },
  { name: 'Libya', 'alpha-2': 'LY' },
  { name: 'Liechtenstein', 'alpha-2': 'LI' },
  { name: 'Lithuania', 'alpha-2': 'LT' },
  { name: 'Luxembourg', 'alpha-2': 'LU' },
  { name: 'Macao', 'alpha-2': 'MO' },
  { name: 'Madagascar', 'alpha-2': 'MG' },
  { name: 'Malawi', 'alpha-2': 'MW' },
  { name: 'Malaysia', 'alpha-2': 'MY' },
  { name: 'Maldives', 'alpha-2': 'MV' },
  { name: 'Mali', 'alpha-2': 'ML' },
  { name: 'Malta', 'alpha-2': 'MT' },
  { name: 'Marshall Islands', filename: 'marshall-island', 'alpha-2': 'MH' },
  { name: 'Martinique', 'alpha-2': 'MQ' },
  { name: 'Mauritania', 'alpha-2': 'MR' },
  { name: 'Mauritius', 'alpha-2': 'MU' },
  { name: 'Mexico', 'alpha-2': 'MX' },
  { name: 'Micronesia (Federated States of)', filename: 'micronesia', 'alpha-2': 'FM' },
  { name: 'Moldova, Republic of', filename: 'moldova', 'alpha-2': 'MD' },
  { name: 'Monaco', 'alpha-2': 'MC' },
  { name: 'Mongolia', 'alpha-2': 'MN' },
  { name: 'Montenegro', 'alpha-2': 'ME' },
  { name: 'Montserrat', 'alpha-2': 'MS' },
  { name: 'Morocco', 'alpha-2': 'MA' },
  { name: 'Mozambique', 'alpha-2': 'MZ' },
  { name: 'Myanmar', 'alpha-2': 'MM' },
  { name: 'Namibia', 'alpha-2': 'NA' },
  { name: 'Nauru', 'alpha-2': 'NR' },
  { name: 'Nepal', 'alpha-2': 'NP' },
  { name: 'Netherlands', 'alpha-2': 'NL' },
  { name: 'New Zealand', 'alpha-2': 'NZ' },
  { name: 'Nicaragua', 'alpha-2': 'NI' },
  { name: 'Niger', 'alpha-2': 'NE' },
  { name: 'Nigeria', 'alpha-2': 'NG' },
  { name: 'Niue', 'alpha-2': 'NU' },
  { name: 'Norfolk Island', 'alpha-2': 'NF' },
  { name: 'North Macedonia', 'alpha-2': 'MK' },
  { name: 'Northern Mariana Islands', filename: 'northern-marianas-islands', 'alpha-2': 'MP' },
  { name: 'Norway', 'alpha-2': 'NO' },
  { name: 'Oman', 'alpha-2': 'OM' },
  { name: 'Pakistan', 'alpha-2': 'PK' },
  { name: 'Palau', 'alpha-2': 'PW' },
  { name: 'Palestine, State of', filename: 'palestine', 'alpha-2': 'PS' },
  { name: 'Panama', 'alpha-2': 'PA' },
  { name: 'Papua New Guinea', filename: 'papua-new-guinea', 'alpha-2': 'PG' },
  { name: 'Paraguay', 'alpha-2': 'PY' },
  { name: 'Peru', 'alpha-2': 'PE' },
  { name: 'Philippines', 'alpha-2': 'PH' },
  { name: 'Pitcairn', filename: 'pitcairn-islands', 'alpha-2': 'PN' },
  { name: 'Poland', filename: 'republic-of-poland', 'alpha-2': 'PL' },
  { name: 'Portugal', 'alpha-2': 'PT' },
  { name: 'Puerto Rico', 'alpha-2': 'PR' },
  { name: 'Qatar', 'alpha-2': 'QA' },
  { name: 'Romania', 'alpha-2': 'RO' },
  { name: 'Russian Federation', filename: 'russia', 'alpha-2': 'RU' },
  { name: 'Rwanda', 'alpha-2': 'RW' },
  { name: 'Saint Kitts and Nevis', filename: 'saint-kitts-and-nevis', 'alpha-2': 'KN' },
  { name: 'Saint Lucia', filename: 'st-lucia', 'alpha-2': 'LC' },
  { name: 'Saint Vincent and the Grenadines', filename: 'st-vincent-and-the-grenadines', 'alpha-2': 'VC' },
  { name: 'Samoa', 'alpha-2': 'WS' },
  { name: 'San Marino', 'alpha-2': 'SM' },
  { name: 'Sao Tome and Principe', filename: 'sao-tome-and-principe', 'alpha-2': 'ST' },
  { name: 'Saudi Arabia', 'alpha-2': 'SA' },
  { name: 'Senegal', 'alpha-2': 'SN' },
  { name: 'Serbia', 'alpha-2': 'RS' },
  { name: 'Seychelles', 'alpha-2': 'SC' },
  { name: 'Sierra Leone', 'alpha-2': 'SL' },
  { name: 'Singapore', 'alpha-2': 'SG' },
  { name: 'Slovakia', 'alpha-2': 'SK' },
  { name: 'Slovenia', 'alpha-2': 'SI' },
  { name: 'Solomon Islands', 'alpha-2': 'SB' },
  { name: 'Somalia', 'alpha-2': 'SO' },
  { name: 'South Africa', 'alpha-2': 'ZA' },
  { name: 'South Sudan', 'alpha-2': 'SS' },
  { name: 'Spain', 'alpha-2': 'ES' },
  { name: 'Sri Lanka', 'alpha-2': 'LK' },
  { name: 'Sudan', 'alpha-2': 'SD' },
  { name: 'Suriname', 'alpha-2': 'SR' },
  { name: 'Sweden', 'alpha-2': 'SE' },
  { name: 'Switzerland', 'alpha-2': 'CH' },
  { name: 'Syrian Arab Republic', filename: 'syria', 'alpha-2': 'SY' },
  { name: 'Taiwan, Province of China', filename: 'taiwan', 'alpha-2': 'TW' },
  { name: 'Tajikistan', 'alpha-2': 'TJ' },
  { name: 'Tanzania, United Republic of', filename: 'tanzania', 'alpha-2': 'TZ' },
  { name: 'Thailand', 'alpha-2': 'TH' },
  { name: 'Timor-Leste', filename: 'east-timor', 'alpha-2': 'TL' },
  { name: 'Togo', 'alpha-2': 'TG' },
  { name: 'Tokelau', 'alpha-2': 'TK' },
  { name: 'Tonga', 'alpha-2': 'TO' },
  { name: 'Trinidad and Tobago', filename: 'trinidad-and-tobago', 'alpha-2': 'TT' },
  { name: 'Tunisia', 'alpha-2': 'TN' },
  { name: 'Turkey', 'alpha-2': 'TR' },
  { name: 'Turkmenistan', 'alpha-2': 'TM' },
  { name: 'Turks and Caicos Islands', filename: 'turks-and-caicos', 'alpha-2': 'TC' },
  { name: 'Tuvalu', 'alpha-2': 'TV' },
  { name: 'Uganda', 'alpha-2': 'UG' },
  { name: 'Ukraine', 'alpha-2': 'UA' },
  { name: 'United Arab Emirates', filename: 'united-arab-emirates', 'alpha-2': 'AE' },
  { name: 'United Kingdom of Great Britain and Northern Ireland', filename: 'united-kingdom', 'alpha-2': 'GB' },
  { name: 'United States of America', filename: 'united-states-of-america', 'alpha-2': 'US' },
  { name: 'Uruguay', 'alpha-2': 'UY' },
  { name: 'Uzbekistan', filename: 'uzbekistn', 'alpha-2': 'UZ' },
  { name: 'Vanuatu', 'alpha-2': 'VU' },
  { name: 'Venezuela (Bolivarian Republic of)', filename: 'venezuela', 'alpha-2': 'VE' },
  { name: 'Viet Nam', filename: 'vietnam', 'alpha-2': 'VN' },
  { name: 'Virgin Islands (British)', filename: 'british-virgin-islands', 'alpha-2': 'VG' },
  { name: 'Virgin Islands (U.S.)', filename: 'virgin-islands', 'alpha-2': 'VI' },
  { name: 'Western Sahara', 'alpha-2': 'EH' },
  { name: 'Yemen', 'alpha-2': 'YE' },
  { name: 'Zambia', 'alpha-2': 'ZM' },
  { name: 'Zimbabwe', 'alpha-2': 'ZW' }
]

export const FIAT_COUNTRY: { [string]: { countryName: string, fiatName: string, logoUrl: string } } = {
  AFN: { countryName: 'AFGHANISTAN', logoUrl: `${FLAG_LOGO_URL}/afghanistan.png`, fiatName: 'Afghani' },
  ALL: { countryName: 'ALBANIA', logoUrl: `${FLAG_LOGO_URL}/albania.png`, fiatName: 'Lek' },
  DZD: { countryName: 'ALGERIA', logoUrl: `${FLAG_LOGO_URL}/algeria.png`, fiatName: 'Algerian Dinar' },
  USD: { countryName: 'United States of America', logoUrl: `${FLAG_LOGO_URL}/united-states-of-america.png`, fiatName: 'United States Dollar' },
  EUR: { countryName: 'European Union', logoUrl: `${FLAG_LOGO_URL}/european-union.png`, fiatName: 'Euro' },
  AOA: { countryName: 'ANGOLA', logoUrl: `${FLAG_LOGO_URL}/angola.png`, fiatName: 'Kwanza' },
  XCD: {
    countryName: 'SAINT VINCENT AND THE GRENADINES',
    logoUrl: `${FLAG_LOGO_URL}/st-vincent-and-the-grenadines.png`,
    fiatName: 'East Caribbean Dollar'
  },
  '': { countryName: '-', logoUrl: '', fiatName: 'No universal currency' },
  ARS: { countryName: 'ARGENTINA', logoUrl: `${FLAG_LOGO_URL}/argentina.png`, fiatName: 'Argentine Peso' },
  AMD: { countryName: 'ARMENIA', logoUrl: `${FLAG_LOGO_URL}/armenia.png`, fiatName: 'Armenian Dram' },
  AWG: { countryName: 'ARUBA', logoUrl: `${FLAG_LOGO_URL}/aruba.png`, fiatName: 'Aruban Florin' },
  AUD: { countryName: 'TUVALU', logoUrl: `${FLAG_LOGO_URL}/tuvalu.png`, fiatName: 'Australian Dollar' },
  AZN: { countryName: 'AZERBAIJAN', logoUrl: `${FLAG_LOGO_URL}/azerbaijan.png`, fiatName: 'Azerbaijanian Manat' },
  BSD: { countryName: '-', logoUrl: '', fiatName: 'Bahamian Dollar' },
  BHD: { countryName: 'BAHRAIN', logoUrl: `${FLAG_LOGO_URL}/bahrain.png`, fiatName: 'Bahraini Dinar' },
  BDT: { countryName: 'BANGLADESH', logoUrl: `${FLAG_LOGO_URL}/bangladesh.png`, fiatName: 'Taka' },
  BBD: { countryName: 'BARBADOS', logoUrl: `${FLAG_LOGO_URL}/barbados.png`, fiatName: 'Barbados Dollar' },
  BYN: { countryName: 'BELARUS', logoUrl: `${FLAG_LOGO_URL}/belarus.png`, fiatName: 'Belarussian Ruble' },
  BZD: { countryName: 'BELIZE', logoUrl: `${FLAG_LOGO_URL}/belize.png`, fiatName: 'Belize Dollar' },
  XOF: { countryName: 'TOGO', logoUrl: `${FLAG_LOGO_URL}/togo.png`, fiatName: 'CFA Franc BCEAO' },
  BMD: { countryName: 'BERMUDA', logoUrl: `${FLAG_LOGO_URL}/bermuda.png`, fiatName: 'Bermudian Dollar' },
  BTN: { countryName: 'BHUTAN', logoUrl: `${FLAG_LOGO_URL}/bhutan.png`, fiatName: 'Ngultrum' },
  INR: { countryName: 'INDIA', logoUrl: `${FLAG_LOGO_URL}/india.png`, fiatName: 'Indian Rupee' },
  BOB: { countryName: 'BOLIVIA (PLURINATIONAL STATE OF)', logoUrl: `${FLAG_LOGO_URL}/bolivia.png`, fiatName: 'Boliviano' },
  BOV: { countryName: 'BOLIVIA (PLURINATIONAL STATE OF)', logoUrl: `${FLAG_LOGO_URL}/bolivia.png`, fiatName: 'Mvdol' },
  BAM: { countryName: 'BOSNIA AND HERZEGOVINA', logoUrl: `${FLAG_LOGO_URL}/bosnia-and-herzegovina.png`, fiatName: 'Convertible Mark' },
  BWP: { countryName: 'BOTSWANA', logoUrl: `${FLAG_LOGO_URL}/botswana.png`, fiatName: 'Pula' },
  NOK: { countryName: '-', logoUrl: '', fiatName: 'Norwegian Krone' },
  BRL: { countryName: 'BRAZIL', logoUrl: `${FLAG_LOGO_URL}/brazil.png`, fiatName: 'Brazilian Real' },
  BND: { countryName: 'BRUNEI DARUSSALAM', logoUrl: `${FLAG_LOGO_URL}/brunei.png`, fiatName: 'Brunei Dollar' },
  BGN: { countryName: 'BULGARIA', logoUrl: `${FLAG_LOGO_URL}/bulgaria.png`, fiatName: 'Bulgarian Lev' },
  BIF: { countryName: 'BURUNDI', logoUrl: `${FLAG_LOGO_URL}/burundi.png`, fiatName: 'Burundi Franc' },
  CVE: { countryName: 'CABO VERDE', logoUrl: `${FLAG_LOGO_URL}/cape-verde.png`, fiatName: 'Cabo Verde Escudo' },
  KHR: { countryName: 'CAMBODIA', logoUrl: `${FLAG_LOGO_URL}/cambodia.png`, fiatName: 'Riel' },
  XAF: { countryName: 'GABON', logoUrl: `${FLAG_LOGO_URL}/gabon.png`, fiatName: 'CFA Franc BEAC' },
  CAD: { countryName: 'CANADA', logoUrl: `${FLAG_LOGO_URL}/canada.png`, fiatName: 'Canadian Dollar' },
  KYD: { countryName: '-', logoUrl: '', fiatName: 'Cayman Islands Dollar' },
  CLF: { countryName: 'CHILE', logoUrl: `${FLAG_LOGO_URL}/chile.png`, fiatName: 'Unidad de Fomento' },
  CLP: { countryName: 'CHILE', logoUrl: `${FLAG_LOGO_URL}/chile.png`, fiatName: 'Chilean Peso' },
  CNY: { countryName: 'CHINA', logoUrl: `${FLAG_LOGO_URL}/china.png`, fiatName: 'Yuan Renminbi' },
  COP: { countryName: 'COLOMBIA', logoUrl: `${FLAG_LOGO_URL}/colombia.png`, fiatName: 'Colombian Peso' },
  COU: { countryName: 'COLOMBIA', logoUrl: `${FLAG_LOGO_URL}/colombia.png`, fiatName: 'Unidad de Valor Real' },
  KMF: { countryName: '-', logoUrl: '', fiatName: 'Comoro Franc' },
  CDF: { countryName: '-', logoUrl: '', fiatName: 'Congolese Franc' },
  NZD: { countryName: 'TOKELAU', logoUrl: `${FLAG_LOGO_URL}/tokelau.png`, fiatName: 'New Zealand Dollar' },
  CRC: { countryName: 'COSTA RICA', logoUrl: `${FLAG_LOGO_URL}/costa-rica.png`, fiatName: 'Costa Rican Colon' },
  HRK: { countryName: 'CROATIA', logoUrl: `${FLAG_LOGO_URL}/croatia.png`, fiatName: 'Kuna' },
  CUC: { countryName: 'CUBA', logoUrl: `${FLAG_LOGO_URL}/cuba.png`, fiatName: 'Peso Convertible' },
  CUP: { countryName: 'CUBA', logoUrl: `${FLAG_LOGO_URL}/cuba.png`, fiatName: 'Cuban Peso' },
  ANG: { countryName: '-', logoUrl: '', fiatName: 'Netherlands Antillean Guilder' },
  CZK: { countryName: '-', logoUrl: '', fiatName: 'Czech Koruna' },
  DKK: { countryName: 'GREENLAND', logoUrl: `${FLAG_LOGO_URL}/greenland.png`, fiatName: 'Danish Krone' },
  DJF: { countryName: 'DJIBOUTI', logoUrl: `${FLAG_LOGO_URL}/djibouti.png`, fiatName: 'Djibouti Franc' },
  DOP: { countryName: '-', logoUrl: '', fiatName: 'Dominican Peso' },
  EGP: { countryName: 'EGYPT', logoUrl: `${FLAG_LOGO_URL}/egypt.png`, fiatName: 'Egyptian Pound' },
  SVC: { countryName: 'EL SALVADOR', logoUrl: `${FLAG_LOGO_URL}/salvador.png`, fiatName: 'El Salvador Colon' },
  ERN: { countryName: 'ERITREA', logoUrl: `${FLAG_LOGO_URL}/eritrea.png`, fiatName: 'Nakfa' },
  ETB: { countryName: 'ETHIOPIA', logoUrl: `${FLAG_LOGO_URL}/ethiopia.png`, fiatName: 'Ethiopian Birr' },
  FKP: { countryName: '-', logoUrl: '', fiatName: 'Falkland Islands Pound' },
  FJD: { countryName: 'FIJI', logoUrl: `${FLAG_LOGO_URL}/fiji.png`, fiatName: 'Fiji Dollar' },
  XPF: { countryName: '-', logoUrl: '', fiatName: 'CFP Franc' },
  GMD: { countryName: '-', logoUrl: '', fiatName: 'Dalasi' },
  GEL: { countryName: 'GEORGIA', logoUrl: `${FLAG_LOGO_URL}/georgia.png`, fiatName: 'Lari' },
  GHS: { countryName: 'GHANA', logoUrl: `${FLAG_LOGO_URL}/ghana.png`, fiatName: 'Ghana Cedi' },
  GIP: { countryName: 'GIBRALTAR', logoUrl: `${FLAG_LOGO_URL}/gibraltar.png`, fiatName: 'Gibraltar Pound' },
  GTQ: { countryName: 'GUATEMALA', logoUrl: `${FLAG_LOGO_URL}/guatemala.png`, fiatName: 'Quetzal' },
  GBP: { countryName: '-', logoUrl: `${FLAG_LOGO_URL}/united-kingdom.png`, fiatName: 'Pound Sterling' },
  GNF: { countryName: 'GUINEA', logoUrl: `${FLAG_LOGO_URL}/guinea.png`, fiatName: 'Guinea Franc' },
  GYD: { countryName: 'GUYANA', logoUrl: `${FLAG_LOGO_URL}/guyana.png`, fiatName: 'Guyana Dollar' },
  HTG: { countryName: 'HAITI', logoUrl: `${FLAG_LOGO_URL}/haiti.png`, fiatName: 'Gourde' },
  HNL: { countryName: 'HONDURAS', logoUrl: `${FLAG_LOGO_URL}/honduras.png`, fiatName: 'Lempira' },
  HKD: { countryName: 'HONG KONG', logoUrl: `${FLAG_LOGO_URL}/hong-kong.png`, fiatName: 'Hong Kong Dollar' },
  HUF: { countryName: 'HUNGARY', logoUrl: `${FLAG_LOGO_URL}/hungary.png`, fiatName: 'Forint' },
  ISK: { countryName: 'ICELAND', logoUrl: `${FLAG_LOGO_URL}/iceland.png`, fiatName: 'Iceland Krona' },
  IDR: { countryName: 'INDONESIA', logoUrl: `${FLAG_LOGO_URL}/indonesia.png`, fiatName: 'Rupiah' },
  XDR: { countryName: '-', logoUrl: '', fiatName: 'SDR (Special Drawing Right)' },
  IRR: { countryName: 'IRAN (ISLAMIC REPUBLIC OF)', logoUrl: `${FLAG_LOGO_URL}/iran.png`, fiatName: 'Iranian Rial' },
  IQD: { countryName: 'IRAQ', logoUrl: `${FLAG_LOGO_URL}/iraq.png`, fiatName: 'Iraqi Dinar' },
  ILS: { countryName: 'ISRAEL', logoUrl: `${FLAG_LOGO_URL}/israel.png`, fiatName: 'New Israeli Sheqel' },
  JMD: { countryName: 'JAMAICA', logoUrl: `${FLAG_LOGO_URL}/jamaica.png`, fiatName: 'Jamaican Dollar' },
  JPY: { countryName: 'JAPAN', logoUrl: `${FLAG_LOGO_URL}/japan.png`, fiatName: 'Yen' },
  JOD: { countryName: 'JORDAN', logoUrl: `${FLAG_LOGO_URL}/jordan.png`, fiatName: 'Jordanian Dinar' },
  KZT: { countryName: 'KAZAKHSTAN', logoUrl: `${FLAG_LOGO_URL}/kazakhstan.png`, fiatName: 'Tenge' },
  KES: { countryName: 'KENYA', logoUrl: `${FLAG_LOGO_URL}/kenya.png`, fiatName: 'Kenyan Shilling' },
  KPW: { countryName: '-', logoUrl: '', fiatName: 'North Korean Won' },
  KRW: { countryName: '-', logoUrl: '', fiatName: 'Won' },
  KWD: { countryName: 'KUWAIT', logoUrl: `${FLAG_LOGO_URL}/kuwait.png`, fiatName: 'Kuwaiti Dinar' },
  KGS: { countryName: 'KYRGYZSTAN', logoUrl: `${FLAG_LOGO_URL}/kyrgyzstan.png`, fiatName: 'Som' },
  LAK: { countryName: '-', logoUrl: '', fiatName: 'Kip' },
  LBP: { countryName: 'LEBANON', logoUrl: `${FLAG_LOGO_URL}/lebanon.png`, fiatName: 'Lebanese Pound' },
  LSL: { countryName: 'LESOTHO', logoUrl: `${FLAG_LOGO_URL}/lesotho.png`, fiatName: 'Loti' },
  ZAR: { countryName: 'SOUTH AFRICA', logoUrl: `${FLAG_LOGO_URL}/south-africa.png`, fiatName: 'Rand' },
  LRD: { countryName: 'LIBERIA', logoUrl: `${FLAG_LOGO_URL}/liberia.png`, fiatName: 'Liberian Dollar' },
  LYD: { countryName: 'LIBYA', logoUrl: `${FLAG_LOGO_URL}/libya.png`, fiatName: 'Libyan Dinar' },
  CHF: { countryName: 'SWITZERLAND', logoUrl: `${FLAG_LOGO_URL}/switzerland.png`, fiatName: 'Swiss Franc' },
  MOP: { countryName: 'MACAO', logoUrl: `${FLAG_LOGO_URL}/macao.png`, fiatName: 'Pataca' },
  MGA: { countryName: 'MADAGASCAR', logoUrl: `${FLAG_LOGO_URL}/madagascar.png`, fiatName: 'Malagasy Ariary' },
  MWK: { countryName: 'MALAWI', logoUrl: `${FLAG_LOGO_URL}/malawi.png`, fiatName: 'Kwacha' },
  MYR: { countryName: 'MALAYSIA', logoUrl: `${FLAG_LOGO_URL}/malaysia.png`, fiatName: 'Malaysian Ringgit' },
  MVR: { countryName: 'MALDIVES', logoUrl: `${FLAG_LOGO_URL}/maldives.png`, fiatName: 'Rufiyaa' },
  MRU: { countryName: 'MAURITANIA', logoUrl: `${FLAG_LOGO_URL}/mauritania.png`, fiatName: 'Ouguiya' },
  MUR: { countryName: 'MAURITIUS', logoUrl: `${FLAG_LOGO_URL}/mauritius.png`, fiatName: 'Mauritius Rupee' },
  XUA: { countryName: '-', logoUrl: '', fiatName: 'ADB Unit of Account' },
  MXN: { countryName: 'MEXICO', logoUrl: `${FLAG_LOGO_URL}/mexico.png`, fiatName: 'Mexican Peso' },
  MXV: { countryName: 'MEXICO', logoUrl: `${FLAG_LOGO_URL}/mexico.png`, fiatName: 'Mexican Unidad de Inversion (UDI)' },
  MDL: { countryName: '-', logoUrl: '', fiatName: 'Moldovan Leu' },
  MNT: { countryName: 'MONGOLIA', logoUrl: `${FLAG_LOGO_URL}/mongolia.png`, fiatName: 'Tugrik' },
  MAD: { countryName: 'WESTERN SAHARA', logoUrl: `${FLAG_LOGO_URL}/western-sahara.png`, fiatName: 'Moroccan Dirham' },
  MZN: { countryName: 'MOZAMBIQUE', logoUrl: `${FLAG_LOGO_URL}/mozambique.png`, fiatName: 'Mozambique Metical' },
  MMK: { countryName: 'MYANMAR', logoUrl: `${FLAG_LOGO_URL}/myanmar.png`, fiatName: 'Kyat' },
  NAD: { countryName: 'NAMIBIA', logoUrl: `${FLAG_LOGO_URL}/namibia.png`, fiatName: 'Namibia Dollar' },
  NPR: { countryName: 'NEPAL', logoUrl: `${FLAG_LOGO_URL}/nepal.png`, fiatName: 'Nepalese Rupee' },
  NIO: { countryName: 'NICARAGUA', logoUrl: `${FLAG_LOGO_URL}/nicaragua.png`, fiatName: 'Cordoba Oro' },
  NGN: { countryName: 'NIGERIA', logoUrl: `${FLAG_LOGO_URL}/nigeria.png`, fiatName: 'Naira' },
  OMR: { countryName: 'OMAN', logoUrl: `${FLAG_LOGO_URL}/oman.png`, fiatName: 'Rial Omani' },
  PKR: { countryName: 'PAKISTAN', logoUrl: `${FLAG_LOGO_URL}/pakistan.png`, fiatName: 'Pakistan Rupee' },
  PAB: { countryName: 'PANAMA', logoUrl: `${FLAG_LOGO_URL}/panama.png`, fiatName: 'Balboa' },
  PGK: { countryName: 'PAPUA NEW GUINEA', logoUrl: `${FLAG_LOGO_URL}/papua-new-guinea.png`, fiatName: 'Kina' },
  PYG: { countryName: 'PARAGUAY', logoUrl: `${FLAG_LOGO_URL}/paraguay.png`, fiatName: 'Guarani' },
  PEN: { countryName: 'PERU', logoUrl: `${FLAG_LOGO_URL}/peru.png`, fiatName: 'Nuevo Sol' },
  PHP: { countryName: '-', logoUrl: '', fiatName: 'Philippine Peso' },
  PLN: { countryName: 'POLAND', logoUrl: `${FLAG_LOGO_URL}/republic-of-poland.png`, fiatName: 'Zloty' },
  QAR: { countryName: 'QATAR', logoUrl: `${FLAG_LOGO_URL}/qatar.png`, fiatName: 'Qatari Rial' },
  MKD: { countryName: '-', logoUrl: '', fiatName: 'Denar' },
  RON: { countryName: 'ROMANIA', logoUrl: `${FLAG_LOGO_URL}/romania.png`, fiatName: 'Romanian Leu' },
  RUB: { countryName: '-', logoUrl: '', fiatName: 'Russian Ruble' },
  RWF: { countryName: 'RWANDA', logoUrl: `${FLAG_LOGO_URL}/rwanda.png`, fiatName: 'Rwanda Franc' },
  SHP: { countryName: '-', logoUrl: '', fiatName: 'Saint Helena Pound' },
  WST: { countryName: 'SAMOA', logoUrl: `${FLAG_LOGO_URL}/samoa.png`, fiatName: 'Tala' },
  STN: { countryName: 'SAO TOME AND PRINCIPE', logoUrl: `${FLAG_LOGO_URL}/sao-tome-and-principe.png`, fiatName: 'Dobra' },
  SAR: { countryName: 'SAUDI ARABIA', logoUrl: `${FLAG_LOGO_URL}/saudi-arabia.png`, fiatName: 'Saudi Riyal' },
  RSD: { countryName: 'SERBIA', logoUrl: `${FLAG_LOGO_URL}/serbia.png`, fiatName: 'Serbian Dinar' },
  SCR: { countryName: 'SEYCHELLES', logoUrl: `${FLAG_LOGO_URL}/seychelles.png`, fiatName: 'Seychelles Rupee' },
  SLL: { countryName: 'SIERRA LEONE', logoUrl: `${FLAG_LOGO_URL}/sierra-leone.png`, fiatName: 'Leone' },
  SGD: { countryName: 'SINGAPORE', logoUrl: `${FLAG_LOGO_URL}/singapore.png`, fiatName: 'Singapore Dollar' },
  XSU: { countryName: '-', logoUrl: '', fiatName: 'Sucre' },
  SBD: { countryName: 'SOLOMON ISLANDS', logoUrl: `${FLAG_LOGO_URL}/solomon-islands.png`, fiatName: 'Solomon Islands Dollar' },
  SOS: { countryName: 'SOMALIA', logoUrl: `${FLAG_LOGO_URL}/somalia.png`, fiatName: 'Somali Shilling' },
  SSP: { countryName: 'SOUTH SUDAN', logoUrl: `${FLAG_LOGO_URL}/south-sudan.png`, fiatName: 'South Sudanese Pound' },
  LKR: { countryName: 'SRI LANKA', logoUrl: `${FLAG_LOGO_URL}/sri-lanka.png`, fiatName: 'Sri Lanka Rupee' },
  SDG: { countryName: '-', logoUrl: '', fiatName: 'Sudanese Pound' },
  SRD: { countryName: 'SURINAME', logoUrl: `${FLAG_LOGO_URL}/suriname.png`, fiatName: 'Surinam Dollar' },
  SZL: { countryName: '-', logoUrl: '', fiatName: 'Lilangeni' },
  SEK: { countryName: 'SWEDEN', logoUrl: `${FLAG_LOGO_URL}/sweden.png`, fiatName: 'Swedish Krona' },
  CHE: { countryName: 'SWITZERLAND', logoUrl: `${FLAG_LOGO_URL}/switzerland.png`, fiatName: 'WIR Euro' },
  CHW: { countryName: 'SWITZERLAND', logoUrl: `${FLAG_LOGO_URL}/switzerland.png`, fiatName: 'WIR Franc' },
  SYP: { countryName: 'SYRIAN ARAB REPUBLIC', logoUrl: `${FLAG_LOGO_URL}/syria.png`, fiatName: 'Syrian Pound' },
  TWD: { countryName: '-', logoUrl: '', fiatName: 'New Taiwan Dollar' },
  TJS: { countryName: 'TAJIKISTAN', logoUrl: `${FLAG_LOGO_URL}/tajikistan.png`, fiatName: 'Somoni' },
  TZS: { countryName: 'TANZANIA, UNITED REPUBLIC OF', logoUrl: `${FLAG_LOGO_URL}/tanzania.png`, fiatName: 'Tanzanian Shilling' },
  THB: { countryName: 'THAILAND', logoUrl: `${FLAG_LOGO_URL}/thailand.png`, fiatName: 'Baht' },
  TOP: { countryName: 'TONGA', logoUrl: `${FLAG_LOGO_URL}/tonga.png`, fiatName: 'Pa’anga' },
  TTD: {
    countryName: 'TRINIDAD AND TOBAGO',
    logoUrl: `${FLAG_LOGO_URL}/trinidad-and-tobago.png`,
    fiatName: 'Trinidad and Tobago Dollar'
  },
  TND: { countryName: 'TUNISIA', logoUrl: `${FLAG_LOGO_URL}/tunisia.png`, fiatName: 'Tunisian Dinar' },
  TRY: { countryName: 'TURKEY', logoUrl: `${FLAG_LOGO_URL}/turkey.png`, fiatName: 'Turkish Lira' },
  TMT: { countryName: 'TURKMENISTAN', logoUrl: `${FLAG_LOGO_URL}/turkmenistan.png`, fiatName: 'Turkmenistan New Manat' },
  UGX: { countryName: 'UGANDA', logoUrl: `${FLAG_LOGO_URL}/uganda.png`, fiatName: 'Uganda Shilling' },
  UAH: { countryName: 'UKRAINE', logoUrl: `${FLAG_LOGO_URL}/ukraine.png`, fiatName: 'Hryvnia' },
  AED: { countryName: '-', logoUrl: '', fiatName: 'UAE Dirham' },
  USN: { countryName: '-', logoUrl: '', fiatName: 'United States Dollar (Next day)' },
  UYI: { countryName: 'URUGUAY', logoUrl: `${FLAG_LOGO_URL}/uruguay.png`, fiatName: 'Uruguay Peso en Unidades Indexadas (URUIURUI)' },
  UYU: { countryName: 'URUGUAY', logoUrl: `${FLAG_LOGO_URL}/uruguay.png`, fiatName: 'Peso Uruguayo' },
  UZS: { countryName: 'UZBEKISTAN', logoUrl: `${FLAG_LOGO_URL}/uzbekistn.png`, fiatName: 'Uzbekistan Sum' },
  VUV: { countryName: 'VANUATU', logoUrl: `${FLAG_LOGO_URL}/vanuatu.png`, fiatName: 'Vatu' },
  VEF: { countryName: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', logoUrl: `${FLAG_LOGO_URL}/venezuela.png`, fiatName: 'Bolivar' },
  VND: { countryName: 'VIET NAM', logoUrl: `${FLAG_LOGO_URL}/vietnam.png`, fiatName: 'Dong' },
  YER: { countryName: 'YEMEN', logoUrl: `${FLAG_LOGO_URL}/yemen.png`, fiatName: 'Yemeni Rial' },
  ZMW: { countryName: 'ZAMBIA', logoUrl: `${FLAG_LOGO_URL}/zambia.png`, fiatName: 'Zambian Kwacha' },
  ZWL: { countryName: 'ZIMBABWE', logoUrl: `${FLAG_LOGO_URL}/zimbabwe.png`, fiatName: 'Zimbabwe Dollar' }
}

// utility for recreating list from https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json
/* const modifiedCountryCodes = COUNTRY_CODES.map(country => {
  return {
    name: country.name,
    'alpha-2': country['alpha-2']
  }
})

console.log(JSON.stringify(modifiedCountryCodes)) */
