export const CHANGE_MINING_FEE_VALUE = 'changeMiningFee'
export const EXCHANGE_MAX_AMOUNT_VALUE ='exchangeMaxAmountValue'
export const HELP_VALUE = 'helpValue'
export const SORT_VALUE = 'sort'
export const RENAME_VALUE = 'rename'
export const ADD_TOKENS_VALUE = 'addTokensValue'
export const DELETE_VALUE = 'delete'
