export const SWAP_VERT = 'swap-vert'
export const ADDRESS_BOOK_O = 'address-book-o'
export const USER_O = 'user-o'
export const TRASH_O = 'trash-o'
export const CLOSE_ICON = 'close'
export const KEYBOARD_ARROW_DOWN='keyboard-arrow-down'
