framework=maestro
device.name=google Pixel 10
device.platform=android
device.osVersion=36
runner.version=1.1.25
runner.driver=uiautomator2
app.id=co.edgesecure.app
app.version=99.99.99
app.build=21000000
