require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source "https://cdn.cocoapods.org/"
source "https://github.com/zcash-hackworks/CocoaPodsSpecs.git"

# Edge change: React Native itself only requires 11.0:
platform :ios, '12.0'

target 'edge' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  # --------------------------------------------------------------------------
  # Edge additions
  # --------------------------------------------------------------------------

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  # Necessary for Zcash
  pod 'react-native-zcash', :path => '../node_modules/react-native-zcash'
  pod 'CNIOAtomics', :modular_headers => true
  pod 'CNIOBoringSSL', :modular_headers => true
  pod 'CNIOBoringSSLShims', :modular_headers => true
  pod 'CNIOLinux', :modular_headers => true
  pod 'CNIODarwin', :modular_headers => true
  pod 'CNIOHTTPParser', :modular_headers => true
  pod 'CNIOWindows', :modular_headers => true
  pod 'CGRPCZlib', :modular_headers => true
  pod 'ZcashLightClientKit', :git => 'https://github.com/zcash/ZcashLightClientKit.git'
end
