def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# Edge addition for Expo:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

# Edge addition to disable advertising ID collection:
$RNFirebaseAnalyticsWithoutAdIdSupport = true
$RNFirebaseAsStaticFramework = true

# The min_ios_version_supported is iOS 13.4 for RN 74:
platform :ios, min_ios_version_supported
prepare_react_native_project!

# Edge addition:
setup_permissions([
  'Camera',
  'Contacts',
  'LocationWhenInUse',
  'Notifications',
])

# Edge modification:
use_frameworks! :linkage => :static

target 'edge' do
  # Edge addition:
  use_modular_headers!

  # Edge addition for Expo:
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )
  end

  # --------------------------------------------------------------------------
  # Edge additions
  # --------------------------------------------------------------------------

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
