/**
 * Generates the CLI's runtime help text from the route declarations.
 *
 * JSDoc is erased at compile time, so `edge-cli help <command>` cannot read it
 * directly. This lifts the prose out of `src/cli/engine/routes/*.ts` into a
 * committed JSON file that the CLI imports, keeping a single copy of every
 * sentence: the comment above the handler.
 *
 * The file is committed, so a fresh clone runs without ever executing this —
 * `src/` never depends on `scripts/`. Regenerated by `npm run prepare`.
 *
 *   node -r sucrase/register scripts/buildCliHelp.ts
 */
import path from 'path'

import { extractRoutes } from './extractRoutes'
import { writeIfChanged } from './writeIfChanged'

const OUT = path.resolve(__dirname, '../src/cli/generated/helpDocs.json')

interface CommandHelp {
  summary: string
  description?: string
  core?: string
  method: string
  path: string
  params?: Record<string, string>
  notes?: string[]
  errors?: string[]
}

/** The command name a route declares, in either the string or object form. */
function commandName(
  raw: string | undefined,
  cli: string | undefined
): string | null {
  if (cli != null) return cli
  if (raw == null) return null
  const m = /command:\s*'([a-z0-9-]+)'/.exec(raw)
  return m != null ? m[1] : null
}

const commands: Record<string, CommandHelp> = {}
for (const r of extractRoutes()) {
  const name = commandName(r.cliRaw, r.cli)
  if (name == null) continue
  const entry: CommandHelp = {
    summary: r.summary,
    method: r.method,
    path: r.routePath
  }
  if (r.description != null) entry.description = r.description
  if (r.core != null) entry.core = r.core
  if (Object.keys(r.params).length > 0) entry.params = r.params
  if (r.notes.length > 0) entry.notes = r.notes
  if (r.errors.length > 0) entry.errors = r.errors
  commands[name] = entry
}

const payload = {
  $comment:
    'GENERATED FILE — DO NOT EDIT. Produced by scripts/buildCliHelp.ts from ' +
    'the JSDoc above each route() in src/cli/engine/routes. Edit the comment ' +
    'on the route, then run `npm run prepare` (or `npm run docs:api`).',
  commands: Object.fromEntries(
    Object.keys(commands)
      .sort((a, b) => a.localeCompare(b))
      .map(k => [k, commands[k]])
  )
}

const changed = writeIfChanged(OUT, JSON.stringify(payload, null, 2) + '\n')
const count = Object.keys(commands).length
console.log(
  `${changed ? '✓ wrote' : '· unchanged'} src/cli/generated/helpDocs.json ` +
    `(${count} command${count === 1 ? '' : 's'})`
)
