/**
 * Generates the CLI's runtime help text from the route declarations.
 *
 * JSDoc is erased at compile time, so `edge-cli help <command>` cannot read it
 * directly. This lifts the prose out of `src/cli/engine/routes/*.ts` into a
 * committed JSON file that the CLI imports, keeping a single copy of every
 * sentence: the declaration itself.
 *
 * The file is committed, so a fresh clone runs without ever executing this —
 * `src/` never depends on `scripts/`. Regenerated by `npm run prepare`.
 *
 *   node -r sucrase/register scripts/buildCliHelp.ts
 */
import path from 'path'

import {
  type ExtractedCli,
  type ExtractedField,
  type ExtractedRoute,
  extractRoutes,
  kebab
} from './extractRoutes'
import { writeIfChanged } from './writeIfChanged'

const OUT = path.resolve(__dirname, '../src/cli/generated/helpDocs.json')

interface ParamHelp {
  /** How to supply it on the command line, or null when REST-only. */
  pass: string | null
  doc?: string
  optional?: boolean
  restOnly?: boolean
}

interface CommandHelp {
  summary: string
  description?: string
  core?: string
  method: string
  path: string
  usage: string
  params?: Record<string, ParamHelp>
  returns?: Record<string, string>
  returnsDoc?: string
  notes?: string[]
  errors?: string[]
}

/** True for a field the command takes as a bare switch rather than a value. */
function isSwitch(type: string): boolean {
  return type.replace(/ \| (null|undefined)/g, '').trim() === 'boolean'
}

/** How a request field is supplied on the command line, if at all. */
function passForm(cli: ExtractedCli, field: ExtractedField): string {
  if (cli.positional === field.name) return `<${field.name}>`
  if (cli.bodyFlag != null) return `--${cli.bodyFlag}='<json>'`
  const mapped = cli.flags.find(f => f.maps === field.name)
  const name = mapped?.name ?? kebab(field.name)
  const token =
    mapped?.repeat === true
      ? `--${name}=<value> …`
      : isSwitch(field.type)
      ? `--${name}`
      : `--${name}=<value>`
  return field.optional ? `[${token}]` : token
}

function usageFor(r: ExtractedRoute, cli: ExtractedCli): string {
  const parts = [cli.command]
  // A positional is a path parameter, so the path is the single source for
  // it; `cli.positional` only names which field it carries.
  for (const p of r.pathParams) if (p !== 'sessionId') parts.push(`<${p}>`)
  if (cli.bodyFlag != null) parts.push(`--${cli.bodyFlag}='<json>'`)
  else {
    for (const f of [...(r.query ?? []), ...(r.body ?? [])]) {
      if (r.pathParams.includes(f.name)) continue
      parts.push(passForm(cli, f))
    }
  }
  for (const x of cli.extra) {
    const token = x.kind === 'boolean' ? `--${x.name}` : `--${x.name}=<value>`
    parts.push(x.required === true ? token : `[${token}]`)
  }
  return parts.join(' ')
}

function helpFor(r: ExtractedRoute, cli: ExtractedCli): CommandHelp {
  const entry: CommandHelp = {
    summary: r.summary,
    method: r.method,
    path: r.routePath,
    usage: usageFor(r, cli)
  }
  if (r.description != null) entry.description = r.description
  if (r.core != null) entry.core = r.core

  const params: Record<string, ParamHelp> = {}
  for (const f of [...(r.query ?? []), ...(r.body ?? [])]) {
    params[f.name] = {
      pass: passForm(cli, f),
      doc: f.doc,
      optional: f.optional
    }
  }
  for (const x of cli.extra) {
    params[x.name] = {
      pass: x.kind === 'boolean' ? `--${x.name}` : `--${x.name}=<value>`,
      doc: x.doc,
      optional: x.required !== true
    }
  }
  if (Object.keys(params).length > 0) entry.params = params

  if (r.returns != null && r.returns.length > 0) {
    entry.returns = Object.fromEntries(
      r.returns.map(f => [
        f.name + (f.optional ? '?' : ''),
        f.doc != null ? `${f.type} — ${f.doc}` : f.type
      ])
    )
  } else if (r.returnsType != null && r.returnsType !== 'unknown') {
    entry.returns = { '': r.returnsType }
  }
  const returnsProse = r.returnsProse ?? r.returnsDoc
  if (returnsProse != null) entry.returnsDoc = returnsProse

  const notes = [...r.notes]
  if (cli.notes != null) notes.push(cli.notes)
  if (notes.length > 0) entry.notes = notes
  if (r.errors.length > 0) entry.errors = r.errors
  return entry
}

const commands: Record<string, CommandHelp> = {}
for (const r of extractRoutes()) {
  for (const cli of [r.cli, ...r.cliExtra]) {
    if (cli == null) continue
    commands[cli.command] = helpFor(r, cli)
  }
}

const payload = {
  $comment:
    'GENERATED FILE — DO NOT EDIT. Produced by scripts/buildCliHelp.ts from ' +
    'the route declarations in src/cli/engine/routes. Edit the declaration, ' +
    'then run `npm run prepare` (or `npm run docs:api`).',
  commands: Object.fromEntries(
    Object.keys(commands)
      .sort((a, b) => a.localeCompare(b))
      .map(k => [k, commands[k]])
  )
}

const changed = writeIfChanged(OUT, JSON.stringify(payload, null, 2) + '\n')
const count = Object.keys(commands).length
console.log(
  `${changed ? '✓ wrote' : '· unchanged'} src/cli/generated/helpDocs.json ` +
    `(${count} command${count === 1 ? '' : 's'})`
)
