/**
 * Generates the CLI's runtime help text from the route declarations.
 *
 * JSDoc is erased at compile time, so `edge-cli help <command>` cannot read it
 * directly. This lifts the prose out of `src/cli/engine/routes/*.ts` into a
 * committed JSON file that the CLI imports, keeping a single copy of every
 * sentence: the declaration itself.
 *
 * The file is committed, so a fresh clone runs without ever executing this —
 * `src/` never depends on `scripts/`. Regenerated by `npm run prepare`.
 *
 *   node -r sucrase/register scripts/buildCliHelp.ts
 */
import path from 'path'

import type {
  CommandHelpInput as CommandHelp,
  ParamHelpInput as ParamHelp
} from '../src/cli/generatedSchemas'
import { cliOptional, extraPassForm, passForm, usageFor } from './cliUsage'
import {
  type ExtractedCli,
  type ExtractedRoute,
  extractRoutes
} from './extractRoutes'
import { writeIfChanged } from './writeIfChanged'

const OUT = path.resolve(__dirname, '../src/cli/generated/helpDocs.json')

function helpFor(r: ExtractedRoute, cli: ExtractedCli): CommandHelp {
  const entry: CommandHelp = {
    summary: cli.summary ?? r.summary,
    method: r.method,
    path: r.routePath,
    usage: usageFor(r, cli)
  }
  if (r.description != null) entry.description = r.description
  if (r.core != null) entry.core = r.core

  const params: Record<string, ParamHelp> = {}
  for (const f of [...(r.query ?? []), ...(r.body ?? [])]) {
    params[f.name] = {
      pass: passForm(cli, f),
      doc: f.doc,
      // The command's optionality, which can differ from the route's — the
      // table and the usage line read it from the same place now, so they
      // cannot say different things about the same flag.
      optional: cliOptional(cli, f)
    }
  }
  for (const x of cli.extra) {
    // Bracketed when optional, like every request field: `passForm` does
    // that and this did not, so the parameter table read as though
    // `get-transactions --out` were required while its own `optional` flag
    // beside it said `true` and the assembled usage line bracketed it.
    const token = extraPassForm(x)
    params[x.name] = {
      pass: x.required === true ? token : `[${token}]`,
      doc: x.doc,
      optional: x.required !== true
    }
  }
  if (Object.keys(params).length > 0) entry.params = params

  if (r.returns != null && r.returns.length > 0) {
    entry.returns = Object.fromEntries(
      r.returns.map(f => [
        f.name + (f.optional ? '?' : ''),
        f.doc != null ? `${f.type} — ${f.doc}` : f.type
      ])
    )
  } else if (r.returnsType != null && r.returnsType !== 'unknown') {
    entry.returns = { '': r.returnsType }
  }
  const returnsProse = r.returnsProse ?? r.returnsDoc
  if (returnsProse != null) entry.returnsDoc = returnsProse

  const notes = [...r.notes]
  if (cli.notes != null) notes.push(cli.notes)
  if (notes.length > 0) entry.notes = notes
  if (r.errors.length > 0) entry.errors = r.errors
  return entry
}

const commands: Record<string, CommandHelp> = {}
for (const r of extractRoutes()) {
  for (const cli of [r.cli, ...r.cliExtra]) {
    if (cli == null) continue
    const entry = helpFor(r, cli)
    const existing = commands[cli.command]
    if (existing == null) {
      commands[cli.command] = entry
      continue
    }
    // Two routes can share a command name — `local-settings` reads on GET and
    // writes on POST. Keeping only the last one meant `help local-settings`
    // showed the write usage alone, so the read form looked invalid. Merge
    // both, so every form the command accepts is described: its usage line,
    // its REST route, the fields a caller can send and what comes back.
    existing.alsoUsage = [...(existing.alsoUsage ?? []), entry.usage]
    existing.alsoRest = [
      ...(existing.alsoRest ?? []),
      `${entry.method} ${entry.path}`
    ]
    existing.description = [
      existing.description,
      `${entry.summary} ${entry.description ?? ''}`.trim()
    ]
      .filter(part => part != null && part !== '')
      .join('\n\n')
    if (entry.params != null) {
      existing.params = { ...(existing.params ?? {}), ...entry.params }
    }
    if (entry.returns != null) {
      existing.returns = { ...(existing.returns ?? {}), ...entry.returns }
    }
    if (entry.errors != null) {
      existing.errors = [
        ...new Set([...(existing.errors ?? []), ...entry.errors])
      ]
    }
  }
}

const payload = {
  $comment:
    'GENERATED FILE — DO NOT EDIT. Produced by scripts/buildCliHelp.ts from ' +
    'the route declarations in src/cli/engine/routes. Edit the declaration, ' +
    'then run `npm run prepare` (or `npm run docs:api`).',
  commands: Object.fromEntries(
    Object.keys(commands)
      .sort((a, b) => a.localeCompare(b))
      .map(k => [k, commands[k]])
  )
}

const changed = writeIfChanged(OUT, JSON.stringify(payload, null, 2) + '\n')
const count = Object.keys(commands).length
console.log(
  `${changed ? '✓ wrote' : '· unchanged'} src/cli/generated/helpDocs.json ` +
    `(${count} command${count === 1 ? '' : 's'})`
)
