import fs from 'fs'
import path from 'path'

function makeNativeHeaders(): void {
  // Grab the API key from edgeKey.json (login HMAC credentials):
  let apiKey = 'Error: Set up edgeKey.json & re-run scripts/makeNativeHeaders.js'
  try {
    apiKey = require('../edgeKey.json').apiKey
  } catch (e) {
    console.log(apiKey)
  }

  // Grab the push notification server:
  let pushServer = 'https://push2.edge.app'
  try {
    pushServer = require('../src/theme/appConfig.js').notificationServers[0]
  } catch (e) {}

  const iosPath = path.join(__dirname, '../ios/EdgeApiKey.swift')
  const iosSource = `/* auto-generated by scripts/makeNativeHeaders.js */

public class EdgeApiKey {
  public static let apiKey = "${apiKey}"
  public static let pushServer = "${pushServer}"
}
`
  fs.writeFileSync(iosPath, iosSource)

  const androidPath = path.join(
    __dirname,
    '../android/app/src/main/java/co/edgesecure/app/EdgeApiKey.java'
  )
  const androidSource = `/* auto-generated by scripts/makeNativeHeaders.js */
package co.edgesecure.app;

public class EdgeApiKey {
  public static final String apiKey = "${apiKey}";
  public static final String pushServer = "${pushServer}";
}
`
  fs.writeFileSync(androidPath, androidSource)
}

try {
  makeNativeHeaders()
} catch (e) {
  console.log(e)
}
