/**
 * Generates XOR-split native C sources embedding apiKey / apiSecret from edgeKey.json.
 *
 * Bundle / application ID for the runtime XOR pad is read from the post-patch
 * project files (must match):
 *   - android/app/build.gradle → applicationId (not namespace)
 *   - ios/edge.xcodeproj/project.pbxproj → PRODUCT_BUNDLE_IDENTIFIER
 *
 * Outputs (gitignored):
 *   ios/EdgeApiSecret.c + ios/EdgeApiSecret.h
 *   android/app/src/main/cpp/edge_api_secret.c (+ header)
 */

import { createHash, randomBytes } from 'crypto'
import fs from 'fs'
import path from 'path'

const ROOT = path.join(__dirname, '..')
const SHARD_COUNT = 6 // 5 random pads + 1 stored remainder (after runtime pad)

function parseHexSecret(hex: string): Buffer {
  const cleaned = hex.replace(/^0x/i, '').trim()
  if (!/^[0-9a-fA-F]*$/.test(cleaned) || cleaned.length % 2 !== 0) {
    throw new Error('apiSecret must be even-length hex')
  }
  return Buffer.from(cleaned, 'hex')
}

function cByteArray(name: string, bytes: Buffer): string {
  const body = Array.from(bytes)
    .map(b => `0x${b.toString(16).padStart(2, '0')}`)
    .join(', ')
  return `static const unsigned char ${name}[${bytes.length}] = { ${body} };\n`
}

/**
 * Read Android applicationId (not namespace) from build.gradle.
 */
export function readAndroidApplicationId(gradlePath: string): string {
  const text = fs.readFileSync(gradlePath, 'utf8')
  const match = text.match(/applicationId\s+"([^"]+)"/)
  if (match == null) {
    throw new Error(`applicationId not found in ${gradlePath}`)
  }
  return match[1]
}

/**
 * Read PRODUCT_BUNDLE_IDENTIFIER from Xcode project.pbxproj.
 * All Debug/Release entries must agree.
 */
export function readIosBundleId(pbxPath: string): string {
  const text = fs.readFileSync(pbxPath, 'utf8')
  const matches = [
    ...text.matchAll(/PRODUCT_BUNDLE_IDENTIFIER\s*=\s*([^;]+);/g)
  ].map(m => m[1].trim().replace(/^"|"$/g, ''))
  if (matches.length === 0) {
    throw new Error(`PRODUCT_BUNDLE_IDENTIFIER not found in ${pbxPath}`)
  }
  const unique = [...new Set(matches)]
  if (unique.length !== 1) {
    throw new Error(
      `Conflicting PRODUCT_BUNDLE_IDENTIFIER values in ${pbxPath}: ${unique.join(
        ', '
      )}`
    )
  }
  return unique[0]
}

/**
 * Canonical app id after any deployPatches: Android applicationId and iOS
 * PRODUCT_BUNDLE_IDENTIFIER must match.
 */
export function readBundleId(root: string = ROOT): string {
  const androidId = readAndroidApplicationId(
    path.join(root, 'android/app/build.gradle')
  )
  const iosId = readIosBundleId(
    path.join(root, 'ios/edge.xcodeproj/project.pbxproj')
  )
  if (androidId !== iosId) {
    throw new Error(
      `Bundle ID mismatch: Android applicationId="${androidId}" vs iOS PRODUCT_BUNDLE_IDENTIFIER="${iosId}"`
    )
  }
  return androidId
}

function makeSource(apiKey: string, secret: Buffer, bundleId: string): string {
  const len = secret.length
  const runtimePad = createHash('sha256')
    .update(bundleId, 'utf8')
    .digest()
    .subarray(0, len)

  // P1..P5 random; stored = S xor P1..P5 xor runtimePad
  const pads: Buffer[] = []
  for (let i = 0; i < SHARD_COUNT - 1; i++) {
    pads.push(randomBytes(len))
  }
  const stored = Buffer.alloc(len)
  for (let i = 0; i < len; i++) {
    let v = secret[i] ^ runtimePad[i]
    for (const p of pads) v ^= p[i]
    stored[i] = v
  }
  pads.push(stored)

  // Decoy arrays (same shape, unused):
  const decoys = [randomBytes(len), randomBytes(len), randomBytes(len)]

  const shardNames = ['ea_s0', 'ea_s1', 'ea_s2', 'ea_s3', 'ea_s4', 'ea_s5']
  const decoyNames = ['ea_d0', 'ea_d1', 'ea_d2']

  let out = `/* auto-generated by scripts/makeApiSigner.ts — do not edit */
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include "edge_hmac.h"
#include "edge_api_sign.h"

#define EDGE_API_SECRET_LEN ${len}

`
  // Interleave shards and decoys:
  for (let i = 0; i < shardNames.length; i++) {
    out += cByteArray(shardNames[i], pads[i])
    if (i < decoyNames.length) {
      out += cByteArray(decoyNames[i], decoys[i])
    }
  }

  out += `
static const char ea_api_key[] = ${JSON.stringify(apiKey)};

const char *edge_api_key(void) {
  return ea_api_key;
}

/* Opaque accessors so the arrays are not one contiguous blob in .rodata order alone. */
static void ea_load0(uint8_t *o) { memcpy(o, ea_s0, EDGE_API_SECRET_LEN); }
static void ea_load1(uint8_t *o) { memcpy(o, ea_s1, EDGE_API_SECRET_LEN); }
static void ea_load2(uint8_t *o) { memcpy(o, ea_s2, EDGE_API_SECRET_LEN); }
static void ea_load3(uint8_t *o) { memcpy(o, ea_s3, EDGE_API_SECRET_LEN); }
static void ea_load4(uint8_t *o) { memcpy(o, ea_s4, EDGE_API_SECRET_LEN); }
static void ea_load5(uint8_t *o) { memcpy(o, ea_s5, EDGE_API_SECRET_LEN); }

int edge_api_hmac_sign(
  const uint8_t *message,
  size_t message_len,
  const char *bundle_id,
  uint8_t signature_out[32]
) {
  uint8_t secret[EDGE_API_SECRET_LEN];
  uint8_t tmp[EDGE_API_SECRET_LEN];
  uint8_t runtime_pad[32];
  edge_sha256_ctx sha;
  size_t i;
  size_t pad_len;

  if (message == NULL || signature_out == NULL || bundle_id == NULL) {
    return 1;
  }

  memset(secret, 0, sizeof(secret));
  ea_load0(tmp); for (i = 0; i < EDGE_API_SECRET_LEN; ++i) secret[i] ^= tmp[i];
  ea_load1(tmp); for (i = 0; i < EDGE_API_SECRET_LEN; ++i) secret[i] ^= tmp[i];
  ea_load2(tmp); for (i = 0; i < EDGE_API_SECRET_LEN; ++i) secret[i] ^= tmp[i];
  ea_load3(tmp); for (i = 0; i < EDGE_API_SECRET_LEN; ++i) secret[i] ^= tmp[i];
  ea_load4(tmp); for (i = 0; i < EDGE_API_SECRET_LEN; ++i) secret[i] ^= tmp[i];
  ea_load5(tmp); for (i = 0; i < EDGE_API_SECRET_LEN; ++i) secret[i] ^= tmp[i];

  edge_sha256_init(&sha);
  edge_sha256_update(&sha, (const uint8_t *)bundle_id, strlen(bundle_id));
  edge_sha256_final(&sha, runtime_pad);
  pad_len = EDGE_API_SECRET_LEN < 32 ? EDGE_API_SECRET_LEN : 32;
  for (i = 0; i < pad_len; ++i) secret[i] ^= runtime_pad[i];

  edge_hmac_sha256(secret, EDGE_API_SECRET_LEN, message, message_len, signature_out);

  edge_secure_wipe(secret, sizeof(secret));
  edge_secure_wipe(tmp, sizeof(tmp));
  edge_secure_wipe(runtime_pad, sizeof(runtime_pad));
  edge_secure_wipe(&sha, sizeof(sha));
  return 0;
}
`
  return out
}

function makeHeader(): string {
  return `/* auto-generated by scripts/makeApiSigner.ts — do not edit */
#ifndef EDGE_API_SECRET_GEN_H
#define EDGE_API_SECRET_GEN_H
#include "edge_api_sign.h"
#endif
`
}

function writeFile(filePath: string, contents: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, contents)
  console.log('wrote', path.relative(ROOT, filePath))
}

function main(): void {
  const bundleId = readBundleId()
  console.log('bundleId', bundleId)

  let apiKey =
    'Error: Set up edgeKey.json apiKey & re-run scripts/makeApiSigner.ts'
  let secretHex = ''
  try {
    const edgeKey = require('../edgeKey.json')
    if (typeof edgeKey.apiKey === 'string' && edgeKey.apiKey !== '') {
      apiKey = edgeKey.apiKey
    }
    if (typeof edgeKey.apiSecret === 'string' && edgeKey.apiSecret !== '') {
      secretHex = edgeKey.apiSecret
    }
  } catch (e) {
    console.log('warn: could not read edgeKey.json')
  }

  if (secretHex === '') {
    // Emit a stub that fails signing so builds still compile without a secret.
    secretHex = '00'
    console.log(
      'warn: apiSecret missing; emitting stub secret (signing will be wrong)'
    )
  }

  const secret = parseHexSecret(secretHex)
  const source = makeSource(apiKey, secret, bundleId)
  const header = makeHeader()

  writeFile(path.join(ROOT, 'ios/EdgeApiSecret.c'), source)
  writeFile(path.join(ROOT, 'ios/EdgeApiSecret.h'), header)

  const androidCpp = path.join(ROOT, 'android/app/src/main/cpp')
  writeFile(path.join(androidCpp, 'edge_api_secret.c'), source)
  writeFile(path.join(androidCpp, 'edge_api_secret.h'), header)
}

try {
  main()
} catch (e) {
  console.error(e)
  process.exit(1)
}
